-- Language file

-- German and English Language by Rene Schneider, Alexander Sheloknev
-- Русский язык доработал Александр Шелохнёв
-- French language is made by Nilyn (EU Dalaran Alliance Server)
-- El idioma español está compuesto por Jsr1976-Fili

BINDING_HEADER_ATSW					= 'Advanced Trade Skill Window 2'

local Locale = GetLocale()

if Locale == 'deDE' then
	ATSW_CLEAR 							= 'Klar'
	ATSW_CREATE 							= 'Schaffen'
	ATSW_STOP 								= 'Halt'
	ATSW_SORTBY 							= 'Sortieren:'
	ATSW_SORTBYCATEGORY 			= 'Kategorie'
	ATSW_SORTBYNAMES 				= 'Name'
	ATSW_SORTBYDIFFICULTY 			= 'Schwierigkeit'
	ATSW_CUSTOMSORTING 			= 'Brauch'
	ATSW_TASK 								= 'Task'
	ATSW_SEARCHLABEL 					= 'Suche'
	ATSW_ATTRIBUTES					= 'Attribute'
	ATSW_REAGENTLIST1 				= 'Zur Herstellung von'
	ATSW_REAGENTLIST2 				= 'werden folgende Reagenzien benötigt:'
	ATSW_REAGENTFRAMETITLE 		= 'Ihre Aufgaben erfordern die folgenden Reagenzien:'
	ATSW_REAGENTBUTTON 			= 'Reagenzien'
	ATSW_REAGENTFRAME_CH1 		= 'Taschen'
	ATSW_REAGENTFRAME_CH2 		= 'Bank'
	ATSW_REAGENTFRAME_CH3 		= 'Twink'
	ATSW_REAGENTFRAME_CH4 		= 'Händler'
	ATSW_ALTLIST1 						= 'in Taschen'
	ATSW_ALTLIST2 						= 'auf der Bank'
	ATSW_ANDMORE						= 'und mehr...'
	
	ATSW_OPTIONS_TITLE 				= 'Advanced Trade Skill Window 2 Aufbau'
	ATSWOFTOTALDISPLAY_TEXT 	= 'Gesamtzahl wird angezeigt:'
	ATSWOFUCB_TEXT 					= 'Unified'
	ATSWOFSCB_TEXT 					= 'Separated'
	ATSWOFTOTALINCLUDE_TEXT 	= 'Die Gesamtzahl umfasst:'
	ATSWOFADDONCOMPAT_TEXT	= 'Kompatibilität mit add-ons'
	ATSWOFIB_TEXT 						= 'Bank'
	ATSWOFIA_TEXT 						= 'Alternative Zeichen'
	ATSWOFIM_TEXT 						= 'Händler'
	ATSWOFAB_TEXT 						= 'Autokauf vom Händler\n|cff808080Kaufen Sie automatisch alles Mögliche und Notwendige für alle Artikel \nin der Aufgabenliste, wenn Sie mit Händlern sprechen|r'
	ATSWOFTB_TEXT 						= 'Kurzinfo zum Rezept\n|cff808080Zeigen Sie einen Tooltip an, wenn ein Mauszeiger über einem Rezept \nin der Rezeptliste schwebt|r'
	ATSWOFSLB_TEXT 					= 'Einkaufsliste des Auktionshauses\n|cff808080Zeigen Sie eine Liste der Gegenstände an, die zum Herstellen aller Gegenstände \nin der Aufgabenliste unter dem Auktionsfenster erforderlich sind|r'
	ATSWOF_INSTALLED					= 'Aktiv'
	ATSWOF_ADDON						= 'Zusatz'
	ATSWOF_EFFECT						= 'Wirkung'
	ATSWOFALDESCRIPTION				= 'Bietet handwerkliche Fertigkeitsstufen\nund Bastelzeit'
	ATSWOFOKAY_TEXT					= 'OKAY'
	
	ATSW_TOOLTIP_NECESSARY 		= 'Benötigte reagenzien:'
	ATSW_TOOLTIP_SKILLUPS			= 'Verbesserung: '
	ATSW_TOOLTIP_POSSESS			=	'Diese charaktere besitzen'
	ATSW_TOOLTIP_BUYABLE 			= '(käuflich)'
	ATSW_TOOLTIP_INBAGS 			= 'Taschen'
	ATSW_TOOLTIP_INBANK 			= 'Bank'
	ATSW_TOOLTIP_ONALTS 			= 'Twinks'
	ATSW_TOOLTIP_SAYREAGENTS	= '\n|cff1eff00Shift + Linksklick|r: |cffffffffFügen Sie alle Reagenzien zum Chat hinzu|r'
	ATSW_TOOLTIP_TO					= ' |cffffffffan|r '
	ATSW_TOOLTIP_YELL				= 'aufschrei'
	ATSW_TOOLTIP_PARTY				= 'gruppe'
	ATSW_TOOLTIP_GUILD				= 'gilde'
	ATSW_TOOLTIP_RAID				= 'raid'
	ATSW_TOOLTIP_ADDITEM			= '\n|cff1eff00Shift + Linksklick|r: |cffffffffAlle Elemente zu Aufgaben hinzufügen|r'
	ATSW_BUYBUTTON_TOPTEXT 	= 'Dieser Händler verkauft Reagenzien, die für Aufgaben benötigt werden, für'
	ATSW_BUYBUTTON_TEXT 			= 'Reagenzien kaufen'
	ATSW_SHOPPINGLISTTITLE 		= 'Erforderliche Reagenzien zum Erstellen aller Elemente in der Aufgabenliste:'
	
	ATSW_TOOLS 							= 'Werkzeug:'
	ATSW_AMOUNT 						= 'Menge:'
	ATSW_ALL 								= 'Alle'
	ATSW_ENCHANT 						= 'Verzaubern'
	
	ATSW_CSBUTTON 						= 'Editor'
	ATSWCS_TITLE 							= 'Benutzerdefinierter Sortiereditor'
	ATSWCS_TRADESKILLLISTTITLE 	= 'Rezepturen'
	ATSWCS_CATEGORYLISTTITLE 	= 'Kategorien'
	ATSWCS_ADDCATEGORYLABEL 	= 'Geben Sie den Kategorienamen ein'
	ATSWCS_ADD 							= 'Addieren'
	ATSWCS_RENAME						= 'Umbenennen'
	ATSWCS_DELETE						= 'Löschen'
	ATSWCS_MOVEUP						= 'Hoch'
	ATSWCS_MOVEDOWN				= 'Runter'
	ATSWCS_CATEGORYNAMETITLE	= 'Name:'
	ATSW_UNCATEGORIZED 			= 'Unkategorisiert'
	
	BINDING_NAME_SHOWHIDE			=	'Anzeigen / Ausblenden'
	
	ATSW_HELP_TITLE					= 'Suchbefehle'
	ATSW_HELP_REAGENT				= ':reagent |cReagens|r|n:r |cReagens|r'
	ATSW_HELP_REAGENT_DESC		= '- rezepte anzeigen, für deren Herstellung |cReagens|r erforderlich ist'
	ATSW_HELP_LEVEL					= ':level |cEben|r|n:level |c1 - 10|r|n:level |c45+|r'
	ATSW_HELP_LEVEL_DESC			= '- zeigt Rezepte, die Gegenstände der Stufe |cEben|r produzieren'
	ATSW_HELP_QUALITY				= ':quality |cQualität|r|n:q |cQualität|r|n:rarity |cQualität|r|n:r |cQualität|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r'
	ATSW_HELP_QUALITY_DESC		= '- zeigt Rezepte, die Gegenstände von |cQualität|r-Qualität herstellen'
	ATSW_HELP_POSSIBLE				= ':possible |cMenge|r|n:possible |c10+|r|n:possible |c1 - 40|r'
	ATSW_HELP_POSSIBLE_DESC		= '- zeigt Rezepte, die |cMenge|r-mal mit Materialien in euren Taschen hergestellt werden können'
	ATSW_HELP_POSSIBLE_TOTAL	= ':possibletotal |cMenge|r'
	ATSW_HELP_POSSIBLE_TOTAL_DESC = '- zeigt Rezepte an, die |cMenge|r-mal mit Materialien in deinen Taschen und Orten hergestellt werden können, die im Optionsmenü angegeben sind (Bank, alternative Charaktere oder Händler)'
	ATSW_HELP_QNAMES					= 'Qualitätsnamen:'
	ATSW_HELP_QNAMES_DESC		= '|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r'
	ATSW_HELP_QCOLORS				= 'Qualitätsfarben:'
	ATSW_HELP_QCOLORS_DESC		= '|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r'
	
	-------------------------------
	--  Attribute patterns       --
	-- deutsche Übersetzung --
	--     by Grok (xAI)          --
	-------------------------------
	
	ATSW_TO = ' für '
	ATSW_FOR = ' für '
	ATSW_OF = ' von '
	ATSW_AND = ' und '
	ATSW_PLUS_THREAT = '+Bedrohung'
	ATSW_MINUS_THREAT = '-Bedrohung'
	ATSW_CAST_TIME = 'Zauberzeit'
	ATSW_INC_HEAL = 'erh. Heil.'
	ATSW_STACK = 'Stapel: '
	ATSW_CHARGES = ' Ladungen'

	ATSW_CHANCE_OF = ' Chance auf '
	ATSW_CHANCE_FOR = 'Chance auf '
	ATSW_RESIST = ' Widerst.'
	ATSW_EVERY = ' alle '
	ATSW_DAMAGE_TO = ' Schaden an '
	ATSW_CHANCE_TO_REDUCE = ' Chance, zu senken '
	ATSW_DAMAGE_ON_HIT = ' Schaden bei Treffer '
	ATSW_AND_DAMAGING = ' und Schaden '
	ATSW_ON_HIT_FOR = ' bei Treffer für '
	ATSW_HEALING = ' Heilung'
	ATSW_SPELL_DAMAGE = ' Zauberschaden'
	ATSW_DAMAGE = ' Schaden'
	ATSW_VAMPIRISM = ' Vampir.'
	ATSW_HEALTH_AND = ' Gesundheit und '

	ATSW_ARMOR = ' Rüstung'
	ATSW_STR = ' Stä.'
	ATSW_AGI = ' Bew.'
	ATSW_STA = ' Ausd.'
	ATSW_INT = ' Int.'
	ATSW_SPI = ' Wil.'
	ATSW_ALL_ATTRIBUTES = ' Attribute'
	ATSW_ALL_RESIST = ' Widerst.'
	ATSW_SLOTS = ' Plätze'

	ATSW_DAMAGE_ABSORB = ' Schaden absorb.'
	ATSW_REFLECT = ' Reflektion'

	ATSW_FISHING = ' Angeln '
	ATSW_DEFENSE = ' Abwehr'
	ATSW_DAMAGE_TAKEN = ' erl. Schaden'
	ATSW_DMG_TAKEN_CRITS_DOTS = ' Schaden von Krit. und DoTs'
	ATSW_SPELL_POWER = ' Zaubermacht'
	ATSW_DAMAGE_FOR = ' Schaden für'
	ATSW_SPELL_DAMAGE_TO = ' Zauberschaden an '
	ATSW_BLOCK = ' Block'
	ATSW_PARRY = ' Parieren'
	ATSW_DODGE = ' Ausweichen'
	ATSW_ATTACK_AND_CASTING_SPEED = ' Angr.- u. Zauberzeit'

	ATSW_DAMAGE_ATTACKER_FOR = ' Schaden gegen Angr. für '
	ATSW_LASTS = ' Hält '
	ATSW_ON_MELEE = ' Nahkampf'

	ATSW_POISONS_OF = ' Gifte von '
	ATSW_TARGETS_ALL_RESIST = ' Widerst. Ziel'
	ATSW_NON_PHYSICAL_DEBUFF = 'nicht-phys. Debuff alle '
	ATSW_SECONDS_FOR = ' Sek. für '
	ATSW_IMMUNITY_TO = 'Immun. gegen '
	ATSW_SHOWS = 'zeigt '
	ATSW_TO_CAST = ' zum Wirken '
	ATSW_REGEN_IF = ' %s Regen. wenn '
	ATSW_CONTROL_MECHANICAL = 'Kontrolle mech. Einheit'
	ATSW_MELEE_SPELL_DAMAGE_AND = ' Nahkampf- u. Zauberschaden und '
	ATSW_MOVEMENT_FOR = ' Bewegung für '

	ATSW_OF_TARGET = ' von Ziel'
	ATSW_SCARES = 'verscheucht '
	ATSW_ATTRACTS_MONSTERS = 'Lockt Monster für '
	ATSW_ATTACK_SPEED_FOR = ' Angr.-Geschw. für '
	ATSW_WILL_FIGHT = 'kämpft für dich 1,5 Min.'
	ATSW_TO_OTHER = ' an '
	ATSW_HIT_FOR = ' Treffer für'
	ATSW_SPELL_HIT_FOR = ' Zaubertreffer für'
	ATSW_CRIT = ' Krit.'
	ATSW_CRIT_FOR = ' Krit. für'
	ATSW_SPELL_CRIT_FOR = ' Zauberkrit. für '
	ATSW_WILL = 'ermöglicht '
	ATSW_DAMAGE_PER = ' Schaden pro'
	ATSW_ATTACK_POWER_IN = ' Angriffskraft in '
	ATSW_ATTACK_POWER = ' Angriffskraft'
	ATSW_RANGED_POWER = ' Fernkampfkraft'
	ATSW_ATTACK_POWER_AGAINST = ' Angriffskraft gegen '
	ATSW_ARMOR_IGNORE = ' Rüstung ignor.'
	ATSW_DPS = ' DPS'
	ATSW_HIT = ' Treffer'
	ATSW_SPELL_HIT = ' Zaubertreffer'
	ATSW_SPELL_CRIT = ' Zauberkrit.'
	ATSW_HEALTH_OVER = ' Gesundheit über '
	ATSW_HEALTH = ' Gesundheit'
	ATSW_MANA = ' Mana'
	ATSW_HEALTH_TO = ' Gesundheit an '

	ATSW_CD_REDUCED_BY = ' Abklingzeit reduziert um '
	ATSW_COST_REDUCED_BY = ' Kosten reduziert um '
	ATSW_MANA_BURN_SILENCE = ' Mana verbr., Stille: '
	ATSW_DAMAGE_TO_YOU = ' Schaden an dir'
	ATSW_RADIUS = 'Radius: '
	ATSW_CHANCE = ' Chance: '
	ATSW_CHANCE_OF_STUN = 'Chance auf Betäubung: '
	ATSW_SECONDS = ' Sek.'
	ATSW_STUN = 'Betäubung: '
	ATSW_DAMAGE_RECEIVED = ' erl. Schaden'
	ATSW_ATTACKER_OF_SPELL_FOR = ' Zauber-Angr. für '
	ATSW_IF_DAMAGED_BY_SPELL = ' bei Zauberschaden, Schild von '
	ATSW_OF_SAME_SCHOOL_FOR = ' gleiche Schule für '
	ATSW_TO_RESTORE = ' wiederherstellen '
	ATSW_HEALTH_IF_DAMAGED = ' Gesundheit bei Schaden '
	ATSW_OVER = ' über '
	ATSW_DAMAGE_TAKEN_BY = ' erl. Schaden von '
	ATSW_CHANCE_TO = ' Chance auf '
	ATSW_ATTACKER_OF_LEVEL = ' Angreifer von max. Stufe '
	ATSW_SPELL_POWER_FOR = ' Zaubermacht für '
	ATSW_OF_LEVEL = ' von Stufe '
	ATSW_AND_ABOVE = ' und höher'
	ATSW_OTHER_DAMAGE = ' %s Schaden'
	ATSW_IMMUNE_TO = 'Immun. gegen '
	ATSW_DISARM = 'entwaffnen'
	ATSW_SHIELD = ' Schild '
	ATSW_DISPEL = 'entzaubern'
	ATSW_POLYMORPH = 'polymorph'
	ATSW_DAMAGE_OVER = ' Schaden über '
	ATSW_DAMAGE_AND = ' Schaden und '
	ATSW_CRIT_FOR_PARTY = ' Krit. Gruppe für '
	ATSW_FOR_PARTY = ' für Gruppe'
	ATSW_HEALTH_ON_SPELL_HIT = ' Gesundheit bei Zaubertreffer'
	ATSW_SPELL_DAMAGE_TAKEN_BY_TARGET = ' Zauberschaden erl. Ziel'
	ATSW_CRIT_OF_NEXT_ATTACK = ' Krit. nächster Angriff in '
	ATSW_MOVEMENT_AND = ' Bewegung und '
	ATSW_ATTACK_SPEED_OF_TARGET = ' Angr.-Geschw. Ziel für '
	ATSW_AND_DRAIN = ' und entzieht '
	ATSW_MANA_ON_HIT = ' Mana bei Treffer'
	ATSW_PROTECTION_FROM = 'Schutz vor '
	ATSW_TARGETS_STAT = ' %1$s Ziel'
	ATSW_MINUS_STEALTH_INVIS = '-Tarnung, -Unsichtbarkeit'

	ATSW_COMPANION = 'Begleiter'
	ATSW_TOY = 'Spielzeug'
	ATSW_CHANCE_TO_RESURRECT = ' Chance, Spieler wiederzubeleben'
	ATSW_PORTAL_TO = 'Portal nach '
	ATSW_TELEPORT_TO = 'Teleport nach '
	ATSW_MIND_CONTROL_FOR = 'Gedankenkontrolle für '
	ATSW_STEALTH_INVISIBILITY_DETECTION = 'Erkennung Tarnung und Unsicht.'
	ATSW_REDUCE_YOUR = 'verkleinert dein '
	ATSW_SIZE = 'Größe'
	ATSW_INCAPACITATE = 'kampfunfähig: '
	ATSW_DAMAGE_ABSORB_FOR = ' Schaden absorb. für '
	ATSW_DISGUISE = 'Verkleidung: '
	ATSW_GORDOK_OGRE = 'Gordok-Oger'
	ATSW_PIRATE_OR_NINJA = 'Pirat oder Ninja'
	ATSW_FLASK_OF_PETRIFICATION = '+Unverwundbarkeit, -Handlungsfähigkeit'

	ATSW_DAMAGE_ON_BLOCK_FOR = 'Schaden bei Block für '
	ATSW_AND_ABOVE = ' und höher'
	
elseif Locale == 'frFR' then
	ATSW_CLEAR 							= 'Nettoyer'
	ATSW_CREATE 							= 'Créer'
	ATSW_STOP 								= 'Arrêt'
	ATSW_SORTBY 							= 'Trier par:'
	ATSW_SORTBYCATEGORY 			= 'Catégorie'
	ATSW_SORTBYDIFFICULTY 			= 'Difficulté'
	ATSW_SORTBYNAMES 				= 'Nom'
	ATSW_CUSTOMSORTING 			= 'Personnalisé'
	ATSW_TASK 								= 'Tâche'
	ATSW_SEARCHLABEL 					= 'Chercher'
	ATSW_ATTRIBUTES					= 'Caractéristiques'
	ATSW_REAGENTLIST1 				= 'Pour produir'
	ATSW_REAGENTLIST2 				= 'les réactifs suivants sont nécessaire:'
	ATSW_REAGENTFRAMETITLE 		= 'Vos tâches nécessitent les réactifs suivants:'
	ATSW_REAGENTBUTTON 			= 'Réactifs'
	ATSW_REAGENTFRAME_CH1 		= 'Sacs'
	ATSW_REAGENTFRAME_CH2 		= 'Banque'
	ATSW_REAGENTFRAME_CH3 		= 'Alts'
	ATSW_REAGENTFRAME_CH4 		= 'Marchand'
	ATSW_ALTLIST1 						= 'dans des sacs'
	ATSW_ALTLIST2 						= 'dans la banque'
	ATSW_ANDMORE						= 'et plus...'
	
	ATSW_OPTIONS_TITLE 				= 'Configuration Advanced Trade Skill Window 2'
	ATSWOFTOTALDISPLAY_TEXT 	= 'Le nombre total est affiché :'
	ATSWOFUCB_TEXT 					= 'Unifié'
	ATSWOFSCB_TEXT 					= 'Séparé'
	ATSWOFTOTALINCLUDE_TEXT 	= 'Le nombre total comprend :'
	ATSWOFADDONCOMPAT_TEXT	= 'Compatibilité avec les ajouts interface'
	ATSWOFIB_TEXT 						= 'La banque'
	ATSWOFIA_TEXT 						= 'Les personnages alternatifs'
	ATSWOFIM_TEXT 						= 'Le marchand'
	ATSWOFAB_TEXT 						= 'Achat automatique auprès d\'un marchand\n|cff808080Achetez automatiquement tout ce qui est possible et nécessaire \npour tous les articles de la liste des tâches lorsque vous parlez aux marchands|r'
	ATSWOFTB_TEXT 						= 'Info-bulle de la recette\n|cff808080Afficher une info-bulle lorsque le curseur de la souris survole \nune recette dans la liste des recettes|r'
	ATSWOFSLB_TEXT 					= 'Liste de courses de la maison de vente aux enchères\n|cff808080Afficher une liste des objets nécessaires à la fabrication de tous \nles objets de la liste des tâches sous la fenêtre d\'enchères|r'
	ATSWOF_INSTALLED					= 'Installed'
	ATSWOF_ADDON						= 'Ajout'
	ATSWOF_EFFECT						= 'Effet'
	ATSWOFALDESCRIPTION				= 'Fournit des niveaux de compétences\net le temps de fabrication'
	ATSWOFOKAY_TEXT					= 'D\'accord'
	
	ATSW_TOOLTIP_NECESSARY 		= 'Réactifs nécessaires:'
	ATSW_TOOLTIP_SKILLUPS			= 'Augmenter: '
	ATSW_TOOLTIP_POSSESS			=	'Ces personnages possèdent'
	ATSW_TOOLTIP_BUYABLE 			= '(Achetable)'
	ATSW_TOOLTIP_INBAGS 			= 'Sacs'
	ATSW_TOOLTIP_INBANK 			= 'Banque'
	ATSW_TOOLTIP_ONALTS 			= 'Alts'
	ATSW_TOOLTIP_SAYREAGENTS	= '\n|cff1eff00Maj. + Clic gauche|r: |cffffffffAjouter tous les réactifs dans le chat|r'
	ATSW_TOOLTIP_TO					= ' |cffffffffà|r '
	ATSW_TOOLTIP_YELL				= 'cri'
	ATSW_TOOLTIP_PARTY				= 'groupe'
	ATSW_TOOLTIP_GUILD				= 'guilde'
	ATSW_TOOLTIP_RAID				= 'raid'
	ATSW_TOOLTIP_ADDITEM			= '\n|cff1eff00Maj. + Clic gauche|r: |cffffffffAjouter tous les éléments aux tâches|r'
	ATSW_BUYBUTTON_TOPTEXT 	= 'Ce marchand vend des réactifs nécessaires aux tâches de'
	ATSW_BUYBUTTON_TEXT 			= 'Acheter des réactifs'
	ATSW_SHOPPINGLISTTITLE 		= 'Réactifs requis pour créer tous les éléments de la liste des tâches:'
	
	ATSW_TOOLS 							= 'Outils:'
	ATSW_AMOUNT 						= 'Montant:'
	ATSW_ALL 								= 'Tout'
	ATSW_ENCHANT 						= 'Enchanter'
	
	ATSW_CSBUTTON 						= 'Editeur'
	ATSWCS_TITLE 							= 'Editeur de Classement personnel'
	ATSWCS_TRADESKILLLISTTITLE 	= 'Recettes'
	ATSWCS_CATEGORYLISTTITLE 	= 'Catégories'
	ATSWCS_ADDCATEGORYLABEL 	= 'Saisissez le nom de la catégorie'
	ATSWCS_ADD 							= 'Ajouter'
	ATSWCS_RENAME						= 'Renommer'
	ATSWCS_DELETE						= 'Supprimer'
	ATSWCS_MOVEUP						= 'En haut'
	ATSWCS_MOVEDOWN				= 'Vers le bas'
	ATSWCS_CATEGORYNAMETITLE 	= 'Nom:'
	ATSW_UNCATEGORIZED 			= 'Non classé'
	
	BINDING_NAME_SHOWHIDE			=	'Afficher / Masquer'
	
	ATSW_HELP_TITLE					= 'Commandes de recherche'
	ATSW_HELP_REAGENT				= ':reagent |cRéactif|r|n:r |cRéactif|r'
	ATSW_HELP_REAGENT_DESC		= '- afficher les recettes qui nécessitent |cRéactif|r pour être fabriquées'
	ATSW_HELP_LEVEL					= ':level |cNiveau|r|n:level |c1 - 10|r|n:level |c45+|r'
	ATSW_HELP_LEVEL_DESC			= '- afficher des recettes qui produisent des objets de niveau |cNiveau|r'
	ATSW_HELP_QUALITY				= ':quality |cQualité|r|n:q |cQualité|r|n:rarity |cQualité|r|n:r |cQualité|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r'
	ATSW_HELP_QUALITY_DESC		= '- montrer des recettes qui produisent des articles de qualité |cQualité|r'
	ATSW_HELP_POSSIBLE				= ':possible |cNombre|r|n:possible |c10+|r|n:possible |c1 - 40|r'
	ATSW_HELP_POSSIBLE_DESC		= '- montrer des recettes qui peuvent être fabriquées |cNombre|r de fois en utilisant des matériaux dans vos sacs'
	ATSW_HELP_POSSIBLE_TOTAL	= ':possibletotal |cNombre|r'
	ATSW_HELP_POSSIBLE_TOTAL_DESC = '- afficher les recettes qui peuvent être fabriquées |cNombre|r de fois en utilisant les matériaux dans vos sacs et les emplacements spécifiés dans le menu des options (Banque, Personnages alternatifs ou Marchand)'
	ATSW_HELP_QNAMES					= 'Noms de qualité:'
	ATSW_HELP_QNAMES_DESC		= '|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r'
	ATSW_HELP_QCOLORS				= 'Couleurs de qualité:'
	ATSW_HELP_QCOLORS_DESC		= '|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r'
	
	----------------------------
	--  Attribute patterns   --
	-- traduction française --
	--     by Grok (xAI)      --
	----------------------------
	
	ATSW_TO = ' pour '
	ATSW_FOR = ' pour '
	ATSW_OF = ' de '
	ATSW_AND = ' et '
	ATSW_PLUS_THREAT = '+menace'
	ATSW_MINUS_THREAT = '-menace'
	ATSW_CAST_TIME = 'temps incant.'
	ATSW_INC_HEAL = 'soins reçus'
	ATSW_STACK = 'cumul : '
	ATSW_CHARGES = ' charges'

	ATSW_CHANCE_OF = ' chance de '
	ATSW_CHANCE_FOR = 'chance de '
	ATSW_RESIST = ' résist.'
	ATSW_EVERY = ' toutes '
	ATSW_DAMAGE_TO = ' dégâts à '
	ATSW_CHANCE_TO_REDUCE = ' chance réduire '
	ATSW_DAMAGE_ON_HIT = ' dégâts toucher '
	ATSW_AND_DAMAGING = ' et dégâts '
	ATSW_ON_HIT_FOR = ' toucher pour '
	ATSW_HEALING = ' soins'
	ATSW_SPELL_DAMAGE = ' dégâts sorts'
	ATSW_DAMAGE = ' dégâts'
	ATSW_VAMPIRISM = ' vampir.'
	ATSW_HEALTH_AND = ' santé et '

	ATSW_ARMOR = ' armure'
	ATSW_STR = ' For.'
	ATSW_AGI = ' Agi.'
	ATSW_STA = ' End.'
	ATSW_INT = ' Int.'
	ATSW_SPI = ' Esp.'
	ATSW_ALL_ATTRIBUTES = ' caract.'
	ATSW_ALL_RESIST = ' résist.'
	ATSW_SLOTS = ' empl.'

	ATSW_DAMAGE_ABSORB = ' absorb. dégâts'
	ATSW_REFLECT = ' réflexion'

	ATSW_FISHING = ' pêche '
	ATSW_DEFENSE = ' déf.'
	ATSW_DAMAGE_TAKEN = ' dégâts subis'
	ATSW_DMG_TAKEN_CRITS_DOTS = ' dégâts crit. et DoTs'
	ATSW_SPELL_POWER = ' puiss. sorts'
	ATSW_DAMAGE_FOR = ' dégâts pour'
	ATSW_SPELL_DAMAGE_TO = ' dégâts sorts à '
	ATSW_BLOCK = ' bloc.'
	ATSW_PARRY = ' parad.'
	ATSW_DODGE = ' esquive'
	ATSW_ATTACK_AND_CASTING_SPEED = ' vit. att. et incant.'

	ATSW_DAMAGE_ATTACKER_FOR = ' dégâts contre att. pour '
	ATSW_LASTS = ' Dure '
	ATSW_ON_MELEE = ' att. mêlée'

	ATSW_POISONS_OF = ' poisons de '
	ATSW_TARGETS_ALL_RESIST = ' résist. cible'
	ATSW_NON_PHYSICAL_DEBUFF = 'débuff non-phys. toutes '
	ATSW_SECONDS_FOR = ' sec. pour '
	ATSW_IMMUNITY_TO = 'immun. à '
	ATSW_SHOWS = 'montre '
	ATSW_TO_CAST = ' pour lancer '
	ATSW_REGEN_IF = ' %s régén. si '
	ATSW_CONTROL_MECHANICAL = 'contrôle unité méca.'
	ATSW_MELEE_SPELL_DAMAGE_AND = ' dégâts mêlée et sorts et '
	ATSW_MOVEMENT_FOR = ' mouvement pour '

	ATSW_OF_TARGET = ' de cible'
	ATSW_SCARES = 'effraie '
	ATSW_ATTRACTS_MONSTERS = 'Attire monstre pour '
	ATSW_ATTACK_SPEED_FOR = ' vit. att. pour '
	ATSW_WILL_FIGHT = 'combat pour 1,5 min.'
	ATSW_TO_OTHER = ' à '
	ATSW_HIT_FOR = ' toucher pour'
	ATSW_SPELL_HIT_FOR = ' toucher sorts pour'
	ATSW_CRIT = ' crit.'
	ATSW_CRIT_FOR = ' crit. pour'
	ATSW_SPELL_CRIT_FOR = ' crit. sorts pour '
	ATSW_WILL = 'permet '
	ATSW_DAMAGE_PER = ' dégâts par'
	ATSW_ATTACK_POWER_IN = ' puiss. att. en '
	ATSW_ATTACK_POWER = ' puiss. att.'
	ATSW_RANGED_POWER = ' puiss. dist.'
	ATSW_ATTACK_POWER_AGAINST = ' puiss. att. contre '
	ATSW_ARMOR_IGNORE = ' ignor. armure'
	ATSW_DPS = ' dps'
	ATSW_HIT = ' toucher'
	ATSW_SPELL_HIT = ' toucher sorts'
	ATSW_SPELL_CRIT = ' crit. sorts'
	ATSW_HEALTH_OVER = ' santé sur '
	ATSW_HEALTH = ' santé'
	ATSW_MANA = ' mana'
	ATSW_HEALTH_TO = ' santé à '

	ATSW_CD_REDUCED_BY = ' k-d réduit de '
	ATSW_COST_REDUCED_BY = ' coût réduit de '
	ATSW_MANA_BURN_SILENCE = ' brûle mana, silence : '
	ATSW_DAMAGE_TO_YOU = ' dégâts à vous'
	ATSW_RADIUS = 'rayon : '
	ATSW_CHANCE = ' chance : '
	ATSW_CHANCE_OF_STUN = 'chance étourd. : '
	ATSW_SECONDS = ' sec.'
	ATSW_STUN = 'étourd. : '
	ATSW_DAMAGE_RECEIVED = ' dégâts reçus'
	ATSW_ATTACKER_OF_SPELL_FOR = ' att. sort pour '
	ATSW_IF_DAMAGED_BY_SPELL = ' si dégâts par sort, bouclier de '
	ATSW_OF_SAME_SCHOOL_FOR = ' même école pour '
	ATSW_TO_RESTORE = ' restaurer '
	ATSW_HEALTH_IF_DAMAGED = ' santé si dégâts '
	ATSW_OVER = ' sur '
	ATSW_DAMAGE_TAKEN_BY = ' dégâts subis de '
	ATSW_CHANCE_TO = ' chance de '
	ATSW_ATTACKER_OF_LEVEL = ' att. de niveau max '
	ATSW_SPELL_POWER_FOR = ' puiss. sorts pour '
	ATSW_OF_LEVEL = ' de niveau '
	ATSW_AND_ABOVE = ' et plus'
	ATSW_OTHER_DAMAGE = ' %s dégâts'
	ATSW_IMMUNE_TO = 'immunisé contre '
	ATSW_DISARM = 'désarmer'
	ATSW_SHIELD = ' bouclier '
	ATSW_DISPEL = 'dissipe'
	ATSW_POLYMORPH = 'polymorphie'
	ATSW_DAMAGE_OVER = ' dégâts sur '
	ATSW_DAMAGE_AND = ' dégâts et '
	ATSW_CRIT_FOR_PARTY = ' crit. groupe pour '
	ATSW_FOR_PARTY = ' pour groupe'
	ATSW_HEALTH_ON_SPELL_HIT = ' santé sur toucher sort'
	ATSW_SPELL_DAMAGE_TAKEN_BY_TARGET = ' dégâts sorts reçus cible'
	ATSW_CRIT_OF_NEXT_ATTACK = ' crit. att. suivante dans '
	ATSW_MOVEMENT_AND = ' mouvement et '
	ATSW_ATTACK_SPEED_OF_TARGET = ' vit. att. cible pour '
	ATSW_AND_DRAIN = ' et draine '
	ATSW_MANA_ON_HIT = ' mana au toucher'
	ATSW_PROTECTION_FROM = 'protection de '
	ATSW_TARGETS_STAT = ' %1$s cible'
	ATSW_MINUS_STEALTH_INVIS = '-furtivité, -invisibilité'

	ATSW_COMPANION = 'compagnon'
	ATSW_TOY = 'jouet'
	ATSW_CHANCE_TO_RESURRECT = ' chance ressusciter joueur'
	ATSW_PORTAL_TO = 'portail vers '
	ATSW_TELEPORT_TO = 'téléport vers '
	ATSW_MIND_CONTROL_FOR = 'contrôle esprit pour '
	ATSW_STEALTH_INVISIBILITY_DETECTION = 'détection furtivité et invis.'
	ATSW_REDUCE_YOUR = 'réduit votre '
	ATSW_SIZE = 'taille'
	ATSW_INCAPACITATE = 'incapacite : '
	ATSW_DAMAGE_ABSORB_FOR = ' absorb. dégâts pour '
	ATSW_DISGUISE = 'déguisement : '
	ATSW_GORDOK_OGRE = 'Ogre Gordok'
	ATSW_PIRATE_OR_NINJA = 'Pirate ou Ninja'
	ATSW_FLASK_OF_PETRIFICATION = '+invincibilité, -capacité d\'agir'

	ATSW_DAMAGE_ON_BLOCK_FOR = 'dégâts bloc pour '
	ATSW_AND_ABOVE = ' et plus'
	
elseif Locale == 'esES' then
	ATSW_CLEAR 							= 'Claro'
	ATSW_CREATE 							= 'Crear'
	ATSW_STOP 								= 'Cancelar'
	ATSW_SORTBY 							= 'Ordenar por:'
	ATSW_SORTBYCATEGORY 			= 'Categoría'
	ATSW_SORTBYDIFFICULTY 			= 'Dificultad'
	ATSW_SORTBYNAMES 				= 'Nombre'
	ATSW_CUSTOMSORTING 			= 'Personalizado'
	ATSW_TASK 								= 'Tarea'
	ATSW_SEARCHLABEL 					= 'Buscar'
	ATSW_ATTRIBUTES					= 'Atributos'
	ATSW_REAGENTLIST1 				= 'La elaboración'
	ATSW_REAGENTLIST2 				= 'requiere los siguientes reactivos:'
	ATSW_REAGENTFRAMETITLE 		= 'Sus tareas requieren los siguientes reactivos:'
	ATSW_REAGENTBUTTON 			= 'Reactivos'
	ATSW_REAGENTFRAME_CH1 		= 'Bolsas'
	ATSW_REAGENTFRAME_CH2 		= 'Banco'
	ATSW_REAGENTFRAME_CH3 		= 'Alt'
	ATSW_REAGENTFRAME_CH4 		= 'Mercader'
	ATSW_ALTLIST1 						= 'en bolsas'
	ATSW_ALTLIST2 						= 'en el banco'
	ATSW_ANDMORE						= 'y más...'
	
	ATSW_OPTIONS_TITLE 				= 'Advanced Trade Skill Window 2 Configuración'
	ATSWOFTOTALDISPLAY_TEXT 	= 'Se muestra el conteo total:'
	ATSWOFUCB_TEXT 					= 'Unificado'
	ATSWOFSCB_TEXT 					= 'Separado'
	ATSWOFTOTALINCLUDE_TEXT 	= 'El recuento total incluye:'
	ATSWOFADDONCOMPAT_TEXT	= 'Compatibilidad con extensiones'
	ATSWOFIB_TEXT 						= 'Banco'
	ATSWOFIA_TEXT 						= 'Personajes alternativos'
	ATSWOFIM_TEXT 						= 'Mercader'
	ATSWOFAB_TEXT 						= 'Autocompra del mercader\n|cff808080Compre automáticamente todo lo posible y necesario para todos \nlos elementos de la lista de tareas cuando hable con los comerciantes|r'
	ATSWOFTB_TEXT 						= 'Información de la receta\n|cff808080Muestre una información sobre herramientas cuando el cursor del mouse \nse desplace sobre una receta en la lista de recetas|r'
	ATSWOFSLB_TEXT 					= 'Lista de compras de la casa de subastas\n|cff808080Muestre una lista de artículos que se requieren para fabricar todos \nlos artículos en la lista de tareas en la ventana de subasta|r'
	ATSWOF_INSTALLED					= 'Activo'
	ATSWOF_ADDON						= 'Extensión'
	ATSWOF_EFFECT						= 'Efecto'
	ATSWOFALDESCRIPTION				= 'Proporciona niveles de habilidad de\ny tiempo de elaboración'
	ATSWOFOKAY_TEXT					= 'BUENO'

	ATSW_TOOLTIP_NECESSARY 		= 'Reactivos necesarios:'
	ATSW_TOOLTIP_SKILLUPS			= 'Aumentar: '
	ATSW_TOOLTIP_POSSESS			=	'Estos personajes poseen'
	ATSW_TOOLTIP_BUYABLE 			= '(adquirible)'
	ATSW_TOOLTIP_INBAGS 			= 'Bolsas'
	ATSW_TOOLTIP_INBANK 			= 'Banco'
	ATSW_TOOLTIP_ONALTS 			= 'Alts'
	ATSW_TOOLTIP_SAYREAGENTS	= '\n|cff1eff00Mayús + Clic izquierdo|r: |cffffffffAgregue todos los reactivos al chat|r'
	ATSW_TOOLTIP_TO					= ' |cffffffffa|r '
	ATSW_TOOLTIP_YELL				= 'grito'
	ATSW_TOOLTIP_PARTY				= 'grupo'
	ATSW_TOOLTIP_GUILD				= 'gremio'
	ATSW_TOOLTIP_RAID				= 'raid'
	ATSW_TOOLTIP_ADDITEM			= '\n|cff1eff00Mayús + Clic izquierdo|r: |cffffffffAgregar todos los elementos a las tareas|r'
	ATSW_BUYBUTTON_TOPTEXT 	= 'Este mercader vende reactivos que son necesarios para las tareas de'
	ATSW_BUYBUTTON_TEXT 			= 'Comprar reactivos'
	ATSW_SHOPPINGLISTTITLE 		= 'Lista de compra que necesitas para producir los objetos de la cola:'
	
	ATSW_TOOLS 							= 'Instrumentos:'
	ATSW_AMOUNT 						= 'Monto:'
	ATSW_ALL 								= 'Todos'
	ATSW_ENCHANT 						= 'Encantar'
	
	ATSW_CSBUTTON 						= 'Editor'
	ATSWCS_TITLE 							= 'Editor de clasificación personalizado'
	ATSWCS_TRADESKILLLISTTITLE 	= 'Recetas'
	ATSWCS_CATEGORYLISTTITLE 	= 'Categorías'
	ATSWCS_ADDCATEGORYLABEL 	= 'Introduce el nombre de la categoría'
	ATSWCS_ADD 							= 'Agregar'
	ATSWCS_RENAME 						= 'Rebautizar'
	ATSWCS_DELETE						= 'Borrar'
	ATSWCS_MOVEUP						= 'Arriba'
	ATSWCS_MOVEDOWN				= 'Abajo'
	ATSWCS_CATEGORYNAMETITLE 	= 'Nombre:'
	ATSW_UNCATEGORIZED 			= 'Sin Categoria'
	
	BINDING_NAME_SHOWHIDE			=	'Mostrar / Ocultar'
	
	ATSW_HELP_TITLE					= 'Comandos de búsqueda'
	ATSW_HELP_REAGENT				= ':reagent |cReactivo|r|n:r |cReactivo|r'
	ATSW_HELP_REAGENT_DESC		= '- mostrar recetas que requieren |cReactivo|r para elaborar'
	ATSW_HELP_LEVEL					= ':level |cNivel|r|n:level |c1 - 10|r|n:level |c45+|r'
	ATSW_HELP_LEVEL_DESC			= '- mostrar recetas que producen artículos de nivel |cNivel|r'
	ATSW_HELP_QUALITY				= ':quality |cCalidad|r|n:q |cCalidad|r|n:rarity |cCalidad|r|n:r |cCalidad|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r'
	ATSW_HELP_QUALITY_DESC		= '- mostrar recetas que producen artículos de |cCalidad|r calidad'
	ATSW_HELP_POSSIBLE				= ':possible |cMonto|r|n:possible |c10+|r|n:possible |c1 - 40|r'
	ATSW_HELP_POSSIBLE_DESC		= '- muestra recetas que se pueden fabricar |cMonto|r veces usando materiales en tus bolsas'
	ATSW_HELP_POSSIBLE_TOTAL	= ':possibletotal |cMonto|r'
	ATSW_HELP_POSSIBLE_TOTAL_DESC = 'muestre recetas que se pueden fabricar |cMonto|r veces usando materiales en sus bolsas y ubicaciones especificadas en el menú de opciones (Banco, Personajes alternativos o Comerciante)'
	ATSW_HELP_QNAMES					= 'Nombres de calidad:'
	ATSW_HELP_QNAMES_DESC		= '|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r'
	ATSW_HELP_QCOLORS				= 'Colores de calidad:'
	ATSW_HELP_QCOLORS_DESC		= '|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r'
	
	------------------------------
	--  Attribute patterns     --
	-- traducción al español --
	--     by Grok (xAI)        --
	------------------------------
	
	ATSW_TO = ' para '
	ATSW_FOR = ' para '
	ATSW_OF = ' de '
	ATSW_AND = ' y '
	ATSW_PLUS_THREAT = '+amenaza'
	ATSW_MINUS_THREAT = '-amenaza'
	ATSW_CAST_TIME = 'tiempo lanz.'
	ATSW_INC_HEAL = 'curación rec.'
	ATSW_STACK = 'acum.: '
	ATSW_CHARGES = ' cargas'

	ATSW_CHANCE_OF = ' prob. de '
	ATSW_CHANCE_FOR = 'prob. de '
	ATSW_RESIST = ' resist.'
	ATSW_EVERY = ' cada '
	ATSW_DAMAGE_TO = ' daño a '
	ATSW_CHANCE_TO_REDUCE = ' prob. reducir '
	ATSW_DAMAGE_ON_HIT = ' daño al golpear '
	ATSW_AND_DAMAGING = ' y daño '
	ATSW_ON_HIT_FOR = ' al golpear para '
	ATSW_HEALING = ' curación'
	ATSW_SPELL_DAMAGE = ' daño hech.'
	ATSW_DAMAGE = ' daño'
	ATSW_VAMPIRISM = ' vampir.'
	ATSW_HEALTH_AND = ' salud y '

	ATSW_ARMOR = ' armadura'
	ATSW_STR = ' Fue.'
	ATSW_AGI = ' Agi.'
	ATSW_STA = ' Agu.'
	ATSW_INT = ' Int.'
	ATSW_SPI = ' Esp.'
	ATSW_ALL_ATTRIBUTES = ' atrib.'
	ATSW_ALL_RESIST = ' resist.'
	ATSW_SLOTS = ' huecos'

	ATSW_DAMAGE_ABSORB = ' absorb. daño'
	ATSW_REFLECT = ' reflejo'

	ATSW_FISHING = ' pesca '
	ATSW_DEFENSE = ' def.'
	ATSW_DAMAGE_TAKEN = ' daño recibido'
	ATSW_DMG_TAKEN_CRITS_DOTS = ' daño crit. y DoTs'
	ATSW_SPELL_POWER = ' poder hech.'
	ATSW_DAMAGE_FOR = ' daño para'
	ATSW_SPELL_DAMAGE_TO = ' daño hech. a '
	ATSW_BLOCK = ' bloqueo'
	ATSW_PARRY = ' parada'
	ATSW_DODGE = ' esquivar'
	ATSW_ATTACK_AND_CASTING_SPEED = ' vel. att. y lanz.'

	ATSW_DAMAGE_ATTACKER_FOR = ' daño contra att. para '
	ATSW_LASTS = ' Dura '
	ATSW_ON_MELEE = ' att. cuerpo'

	ATSW_POISONS_OF = ' venenos de '
	ATSW_TARGETS_ALL_RESIST = ' resist. objetivo'
	ATSW_NON_PHYSICAL_DEBUFF = 'debuff no-fís. cada '
	ATSW_SECONDS_FOR = ' seg. para '
	ATSW_IMMUNITY_TO = 'inmun. a '
	ATSW_SHOWS = 'muestra '
	ATSW_TO_CAST = ' para lanzar '
	ATSW_REGEN_IF = ' %s regen. si '
	ATSW_CONTROL_MECHANICAL = 'control unidad mec.'
	ATSW_MELEE_SPELL_DAMAGE_AND = ' daño cuerpo y hech. y '
	ATSW_MOVEMENT_FOR = ' mov. para '

	ATSW_OF_TARGET = ' de objetivo'
	ATSW_SCARES = 'asusta '
	ATSW_ATTRACTS_MONSTERS = 'Atrae monstruos para '
	ATSW_ATTACK_SPEED_FOR = ' vel. att. para '
	ATSW_WILL_FIGHT = 'lucha por ti 1,5 min.'
	ATSW_TO_OTHER = ' a '
	ATSW_HIT_FOR = ' golpe para'
	ATSW_SPELL_HIT_FOR = ' golpe hech. para'
	ATSW_CRIT = ' crit.'
	ATSW_CRIT_FOR = ' crit. para'
	ATSW_SPELL_CRIT_FOR = ' crit. hech. para '
	ATSW_WILL = 'permite '
	ATSW_DAMAGE_PER = ' daño por'
	ATSW_ATTACK_POWER_IN = ' poder att. en '
	ATSW_ATTACK_POWER = ' poder att.'
	ATSW_RANGED_POWER = ' poder dist.'
	ATSW_ATTACK_POWER_AGAINST = ' poder att. contra '
	ATSW_ARMOR_IGNORE = ' ignor. armadura'
	ATSW_DPS = ' dps'
	ATSW_HIT = ' golpe'
	ATSW_SPELL_HIT = ' golpe hech.'
	ATSW_SPELL_CRIT = ' crit. hech.'
	ATSW_HEALTH_OVER = ' salud en '
	ATSW_HEALTH = ' salud'
	ATSW_MANA = ' maná'
	ATSW_HEALTH_TO = ' salud a '

	ATSW_CD_REDUCED_BY = ' cd reducido en '
	ATSW_COST_REDUCED_BY = ' costo reducido en '
	ATSW_MANA_BURN_SILENCE = ' quema maná, silencio: '
	ATSW_DAMAGE_TO_YOU = ' daño a ti'
	ATSW_RADIUS = 'radio: '
	ATSW_CHANCE = ' prob.: '
	ATSW_CHANCE_OF_STUN = 'prob. aturdir: '
	ATSW_SECONDS = ' seg.'
	ATSW_STUN = 'aturdir: '
	ATSW_DAMAGE_RECEIVED = ' daño recibido'
	ATSW_ATTACKER_OF_SPELL_FOR = ' att. hech. para '
	ATSW_IF_DAMAGED_BY_SPELL = ' si daño por hech., escudo de '
	ATSW_OF_SAME_SCHOOL_FOR = ' misma escuela para '
	ATSW_TO_RESTORE = ' restaurar '
	ATSW_HEALTH_IF_DAMAGED = ' salud si daño '
	ATSW_OVER = ' en '
	ATSW_DAMAGE_TAKEN_BY = ' daño recibido de '
	ATSW_CHANCE_TO = ' prob. de '
	ATSW_ATTACKER_OF_LEVEL = ' att. de nivel máx. '
	ATSW_SPELL_POWER_FOR = ' poder hech. para '
	ATSW_OF_LEVEL = ' de nivel '
	ATSW_AND_ABOVE = ' y más'
	ATSW_OTHER_DAMAGE = ' %s daño'
	ATSW_IMMUNE_TO = 'inmune a '
	ATSW_DISARM = 'desarmar'
	ATSW_SHIELD = ' escudo '
	ATSW_DISPEL = 'disipar'
	ATSW_POLYMORPH = 'polimorfia'
	ATSW_DAMAGE_OVER = ' daño en '
	ATSW_DAMAGE_AND = ' daño y '
	ATSW_CRIT_FOR_PARTY = ' crit. grupo para '
	ATSW_FOR_PARTY = ' para grupo'
	ATSW_HEALTH_ON_SPELL_HIT = ' salud al golpear hech.'
	ATSW_SPELL_DAMAGE_TAKEN_BY_TARGET = ' daño hech. recibido obj.'
	ATSW_CRIT_OF_NEXT_ATTACK = ' crit. sig. att. en '
	ATSW_MOVEMENT_AND = ' mov. y '
	ATSW_ATTACK_SPEED_OF_TARGET = ' vel. att. obj. para '
	ATSW_AND_DRAIN = ' y drenar '
	ATSW_MANA_ON_HIT = ' maná al golpear'
	ATSW_PROTECTION_FROM = 'protección de '
	ATSW_TARGETS_STAT = ' %1$s obj.'
	ATSW_MINUS_STEALTH_INVIS = '-sigilo, -invisibilidad'

	ATSW_COMPANION = 'compañero'
	ATSW_TOY = 'juguete'
	ATSW_CHANCE_TO_RESURRECT = ' prob. resucitar jugador'
	ATSW_PORTAL_TO = 'portal a '
	ATSW_TELEPORT_TO = 'teleport a '
	ATSW_MIND_CONTROL_FOR = 'control mente para '
	ATSW_STEALTH_INVISIBILITY_DETECTION = 'detección sigilo e invis.'
	ATSW_REDUCE_YOUR = 'reduce tu '
	ATSW_SIZE = 'tamaño'
	ATSW_INCAPACITATE = 'incapacitar: '
	ATSW_DAMAGE_ABSORB_FOR = ' absorb. daño para '
	ATSW_DISGUISE = 'disfraz: '
	ATSW_GORDOK_OGRE = 'Ogro Gordok'
	ATSW_PIRATE_OR_NINJA = 'Pirata o Ninja'
	ATSW_FLASK_OF_PETRIFICATION = '+invencibilidad, -capacidad de actuar'
	
	ATSW_DAMAGE_ON_BLOCK_FOR = 'daño al bloquear para '
	ATSW_AND_ABOVE = ' y más'
	
elseif Locale == 'ruRU' then
	ATSW_CLEAR 							= 'Очистить'
	ATSW_CREATE 							= 'Создать'
	ATSW_STOP 								= 'Стоп'
	ATSW_SORTBY 							= 'Сортировка:'
	ATSW_SORTBYCATEGORY 			= 'Категория'
	ATSW_SORTBYNAMES 				= 'Имя'
	ATSW_SORTBYDIFFICULTY 			= 'Навык'
	ATSW_CUSTOMSORTING 			= 'Своя'
	ATSW_TASK 								= 'Задача'
	ATSW_SEARCHLABEL 					= 'Поиск'
	ATSW_ATTRIBUTES					= 'Атрибуты'
	ATSW_REAGENTLIST1 				= 'Создание'
	ATSW_REAGENTLIST2 				= 'требует следующие реагенты:'
	ATSW_REAGENTFRAMETITLE 		= 'Для выполнения задач нужны следующие реагенты:'
	ATSW_REAGENTBUTTON 			= 'Реагенты'
	ATSW_REAGENTFRAME_CH1 		= 'Сумки'
	ATSW_REAGENTFRAME_CH2 		= 'Банк'
	ATSW_REAGENTFRAME_CH3 		= 'Персонажи'
	ATSW_REAGENTFRAME_CH4 		= 'Продавец'
	ATSW_ALTLIST1 						= 'в сумках'
	ATSW_ALTLIST2 						= 'в банке'
	ATSW_ANDMORE						= 'и более...'
	
	ATSW_OPTIONS_TITLE 				= 'Настройки Advanced Trade Skill Window 2'
	ATSWOFTOTALDISPLAY_TEXT 	= 'Количество отображается:'
	ATSWOFUCB_TEXT 					= 'Едино'
	ATSWOFSCB_TEXT 					= 'Раздельно'
	ATSWOFTOTALINCLUDE_TEXT 	= 'Количество включает:'
	ATSWOFADDONCOMPAT_TEXT	= 'Совместимость с аддонами'
	ATSWOFIB_TEXT 						= 'Банк'
	ATSWOFIA_TEXT 						= 'Других персонажей'
	ATSWOFIM_TEXT 						= 'Торговцев'
	ATSWOFAB_TEXT 						= 'Автопокупка у продавца\n|cff808080Автоматически покупать всё возможное и необходимое \nдля всех предметов в списке задач при разговоре с торговцами|r'
	ATSWOFTB_TEXT 						= 'Подсказка для рецептов\n|cff808080Отображение всплывающей подсказки при наведении \nкурсора мыши на рецепт в списке рецептов|r'
	ATSWOFSLB_TEXT 					= 'Список покупок под аукционом\n|cff808080Отображать список предметов, необходимых для создания \nвсех предметов в списке задач под окном аукциона|r'
	ATSWOF_INSTALLED					= 'Включён'
	ATSWOF_ADDON						= 'Аддон'
	ATSWOF_EFFECT						= 'Эффект'
	ATSWOFALDESCRIPTION				= 'Даёт уровни повышения навыка\nи время создания'
	ATSWOFOKAY_TEXT					= 'Закрыть'
	
	ATSW_TOOLTIP_NECESSARY 		= 'Требуемые реагенты:'
	ATSW_TOOLTIP_SKILLUPS			= 'Рост: '
	ATSW_TOOLTIP_POSSESS			=	'Следующие персонажи имеют'
	ATSW_TOOLTIP_BUYABLE 			= '(продаётся)'
	ATSW_TOOLTIP_INBAGS 			= 'Сумки'
	ATSW_TOOLTIP_INBANK 			= 'Банк'
	ATSW_TOOLTIP_ONALTS 			= 'Персы'
	ATSW_TOOLTIP_SAYREAGENTS	= '\n|cff1eff00Shift + ЛКМ|r: |cffffffffСказать список реагентов|r'
	ATSW_TOOLTIP_TO					= ' |cffffffffв|r '
	ATSW_TOOLTIP_YELL				= 'крик'
	ATSW_TOOLTIP_PARTY				= 'группу'
	ATSW_TOOLTIP_GUILD				= 'гильдию'
	ATSW_TOOLTIP_RAID				= 'рейд'
	ATSW_TOOLTIP_ADDITEM			= '\n|cff1eff00Shift + ЛКМ|r: |cffffffffДобавить все предметы в задачи|r'
	ATSW_BUYBUTTON_TOPTEXT 	= 'Этот торговец продаёт реагенты, нужные для задач за'
	ATSW_BUYBUTTON_TEXT 			= 'Купить реагенты'
	ATSW_SHOPPINGLISTTITLE 		= 'Реагенты, нужные для создания предметов в списке заданий:'
	
	ATSW_TOOLS 							= 'Инструменты:'
	ATSW_AMOUNT 						= 'Кол-во:'
	ATSW_ALL 								= 'Все'
	ATSW_ENCHANT 						= 'Зачаровать'
	
	ATSW_CSBUTTON 						= 'Редактор'
	ATSWCS_TITLE 							= 'Редактор сортировки рецептов'
	ATSWCS_TRADESKILLLISTTITLE 	= 'Рецепты'
	ATSWCS_CATEGORYLISTTITLE	= 'Категории'
	ATSWCS_ADDCATEGORYLABEL 	= 'Введи имя категории'
	ATSWCS_ADD 							= 'Добавить'
	ATSWCS_RENAME						= 'Новое имя'
	ATSWCS_DELETE						= 'Удалить'
	ATSWCS_MOVEUP						= 'Вверх'
	ATSWCS_MOVEDOWN				= 'Вниз'
	ATSWCS_CATEGORYNAMETITLE 	= 'Имя:'
	ATSW_UNCATEGORIZED 			= 'Без категории'
	
	BINDING_NAME_SHOWHIDE			=	'Показать / Скрыть'
	
	ATSW_HELP_TITLE					= 'Команды поиска'
	ATSW_HELP_REAGENT				= ':reagent |cРеагент|r|n:r |cРеагент|r'
	ATSW_HELP_REAGENT_DESC		= '- показать рецепты, требующие |cРеагент|r для производства'
	ATSW_HELP_LEVEL					= ':level |cУровень|r|n:level |c1 - 10|r|n:level |c45+|r'
	ATSW_HELP_LEVEL_DESC			= '- показать рецепты, которые производят предметы уровня |cУровень|r'
	ATSW_HELP_QUALITY				= ':quality |cКачество|r|n:q |cКачество|r|n:rarity |cКачество|r|n:r |cКачество|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r'
	ATSW_HELP_QUALITY_DESC		= '- показать рецепты, которые производят предметы качества |cКачество|r'
	ATSW_HELP_POSSIBLE				= ':possible |cКоличество|r|n:possible |c10+|r|n:possible |c1 - 40|r'
	ATSW_HELP_POSSIBLE_DESC		= '- показать рецепты, которые можно произвести |cКоличество|r раз, используя материалы в сумках'
	ATSW_HELP_POSSIBLE_TOTAL	= ':possibletotal |cКоличество|r'
	ATSW_HELP_POSSIBLE_TOTAL_DESC = '- показать рецепты, которые можно произвести |cКоличество|r раз, используя материалы в сумках и местах, указанных в настройках (Банк, Другие персонажи или Торговцы)'
	ATSW_HELP_QNAMES					= 'Названия качества:'
	ATSW_HELP_QNAMES_DESC		= '|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r'
	ATSW_HELP_QCOLORS				= 'Цвета качества:'
	ATSW_HELP_QCOLORS_DESC		= '|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r'
	
	----------------------------
	--  Attribute patterns   --
	--   русский перевод   --
	--     by Grok (xAI)      --
	----------------------------
	
	ATSW_TO = ' на '
	ATSW_FOR = ' на '
	ATSW_AND = ' и '
	ATSW_PLUS_THREAT = '+угроза'
	ATSW_MINUS_THREAT = '-угроза'
	ATSW_CAST_TIME = 'время каста'
	ATSW_INC_HEAL = 'вх. исцеление'
	ATSW_STACK = 'стэк: '
	ATSW_CHARGES = ' зарядов'

	ATSW_FOR = ' на '
	ATSW_CHANCE_OF = ' шанс на '
	ATSW_CHANCE_FOR = 'шанс на '
	ATSW_RESIST = 'сопрот.'
	ATSW_EVERY = ' каждые '
	ATSW_DAMAGE_TO = ' урон в '
	ATSW_CHANCE_TO_REDUCE = ' шанс снизить у цели '
	ATSW_DAMAGE_ON_HIT = ' урон при ударе '
	ATSW_AND_DAMAGING = ' и урона по'
	ATSW_ON_HIT_FOR = ' при ударе на '
	ATSW_HEALING = ' исцеление'
	ATSW_SPELL_DAMAGE = ' урон закл.'
	ATSW_DAMAGE = ' урон'
	ATSW_VAMPIRISM = ' вампиризм'
	ATSW_HEALTH_AND = ' здоровье и '
	
	ATSW_ARMOR = ' брони'
	ATSW_STR = ' сил.'
	ATSW_AGI = ' лов.'
	ATSW_STA = ' вын.'
	ATSW_INT = ' инт.'
	ATSW_SPI = ' дух.'
	ATSW_ALL_ATTRIBUTES = ' все характ.'
	ATSW_ALL_RESIST = ' все сопрот.'
	ATSW_SLOTS = ' мест'
	
	ATSW_DAMAGE_ABSORB = ' поглощ. урона'
	ATSW_REFLECT = ' отражение'
	
	ATSW_FISHING = ' рыбалка '
	ATSW_DEFENSE = ' защита'
	ATSW_DAMAGE_TAKEN = ' урона'
	ATSW_DMG_TAKEN_CRITS_DOTS = ' урона от крит. и ДоТ'
	ATSW_SPELL_POWER = ' сила заклинаний'
	ATSW_DAMAGE_FOR = ' урон на'
	ATSW_SPELL_DAMAGE_TO = ' урон заклинаний в '
	ATSW_BLOCK = ' блок'
	ATSW_PARRY = ' парир.'
	ATSW_DODGE = ' уклон.'
	ATSW_ATTACK_AND_CASTING_SPEED = ' скорость атаки и каста'
	
	ATSW_DAMAGE_ATTACKER_FOR = ' урон в '
	ATSW_LASTS = ' Длится '
	ATSW_ON_MELEE = ' при атаке'
	
	ATSW_POISONS_OF = ' ядов до '
	ATSW_TARGETS_ALL_RESIST = ' все сопрот. цели'
	ATSW_NON_PHYSICAL_DEBUFF = 'нефиз. дебафф каждые '
	ATSW_SECONDS_FOR = ' сек. на '
	ATSW_IMMUNITY_TO = 'иммун. к '
	ATSW_SHOWS = 'покажет '
	ATSW_TO_CAST = ' на произнесение '
	ATSW_REGEN_IF = ' %s реген. при '
	ATSW_CONTROL_MECHANICAL = 'контроль мех. юнита'
	ATSW_MELEE_SPELL_DAMAGE_AND = ' ближний и магический урон и '
	ATSW_MOVEMENT_FOR = ' скорость движения на '
	
	ATSW_OF_TARGET = ' цели'
	ATSW_SCARES = 'пугает '
	ATSW_ATTRACTS_MONSTERS = 'Манит монстров на '
	ATSW_ATTACK_SPEED_FOR = ' скор. атаки на '
	ATSW_WILL_FIGHT = 'будет биться за вас 1.5 мин.'
	ATSW_TO_OTHER = ' для '
	ATSW_HIT_FOR = ' попад. на'
	ATSW_SPELL_HIT_FOR = ' попад. закл. на'
	ATSW_CRIT = ' крит.'
	ATSW_CRIT_FOR = ' крит. на'
	ATSW_SPELL_CRIT_FOR = ' крит. закл. на '
	ATSW_WILL = 'будет '
	ATSW_DAMAGE_PER = ' урон за'
	ATSW_ATTACK_POWER_IN = ' сила атаки в '
	ATSW_ATTACK_POWER = ' сила атаки'
	ATSW_RANGED_POWER = ' сила стрельбы'
	ATSW_ATTACK_POWER_AGAINST = ' сила атаки против '
	ATSW_ARMOR_IGNORE = ' игнор. брони'
	ATSW_DPS = ' урон/сек'
	ATSW_HIT = ' попад.'
	ATSW_SPELL_HIT = ' попад. закл.'
	ATSW_SPELL_CRIT = ' крит. заклинаний'
	ATSW_HEALTH_OVER = ' здоровья за '
	ATSW_HEALTH = ' здоровья'
	ATSW_MANA = ' маны'
	ATSW_HEALTH_TO = ' здоровья для '
	
	ATSW_CD_REDUCED_BY = ' кд снижено на '
	ATSW_COST_REDUCED_BY = ' стоимость снижена на '
	ATSW_MANA_BURN_SILENCE = ' сжиг. маны, молчание: '
	ATSW_DAMAGE_TO_YOU = ' урона вам'
	ATSW_RADIUS = 'радиус:'
	ATSW_CHANCE = ' шанс: '
	ATSW_CHANCE_OF_STUN = 'шанс оглушения:'
	ATSW_SECONDS = ' сек.'
	ATSW_STUN = 'оглушение: '
	ATSW_DAMAGE_RECEIVED = ' получаемый урон'
	ATSW_ATTACKER_OF_SPELL_FOR = ' атакующего закл. на '
	ATSW_IF_DAMAGED_BY_SPELL = ' при уроне от закл. получить щит на '
	ATSW_OF_SAME_SCHOOL_FOR = ' той же школы на '
	ATSW_TO_RESTORE = ' восстановить '
	ATSW_HEALTH_IF_DAMAGED = ' здоровья при уроне '
	ATSW_OVER = ' за '
	ATSW_DAMAGE_TAKEN_BY = ' получ. урон на '
	ATSW_CHANCE_TO = ' шанс '
	ATSW_ATTACKER_OF_LEVEL = ' атакующего до уровня '
	ATSW_SPELL_POWER_FOR = ' сила закл. для '
	ATSW_OF_LEVEL = ' уровня '
	ATSW_AND_ABOVE = ' и выше'
	ATSW_OTHER_DAMAGE = ' %s урона'
	ATSW_IMMUNE_TO = 'иммун. к '
	ATSW_DISARM = 'обезоруживанию'
	ATSW_SHIELD = ' щит '
	ATSW_DISPEL = 'рассеивание'
	ATSW_POLYMORPH = 'овцы'
	ATSW_DAMAGE_OVER = ' урона за '
	ATSW_DAMAGE_AND = ' урона и '
	ATSW_CRIT_FOR_PARTY = ' крит. для группы на '
	ATSW_FOR_PARTY = ' для группы'
	ATSW_HEALTH_ON_SPELL_HIT = ' здоровья при попад. закл.'
	ATSW_SPELL_DAMAGE_TAKEN_BY_TARGET = ' получаемый урон от закл. цели'
	ATSW_CRIT_OF_NEXT_ATTACK = ' крит. след. атаки в течение '
	ATSW_MOVEMENT_AND = ' движения и '
	ATSW_ATTACK_SPEED_OF_TARGET = ' скорость атаки цели на '
	ATSW_AND_DRAIN = ' и отнять у цели '
	ATSW_MANA_ON_HIT = ' маны при ударе'
	ATSW_PROTECTION_FROM = 'защита от '
	ATSW_TARGETS_STAT = ' %1$s у цели'
	ATSW_MINUS_STEALTH_INVIS = '-скрытность, -невидимость'
	
	ATSW_COMPANION = 'спутник'
	ATSW_TOY = 'игрушка'
	ATSW_CHANCE_TO_RESURRECT = ' шанс воскресить игрока'
	ATSW_PORTAL_TO = 'портал в '
	ATSW_TELEPORT_TO = 'телепорт в '
	ATSW_MIND_CONTROL_FOR = 'контроль разума на '
	ATSW_STEALTH_INVISIBILITY_DETECTION = 'обнаружение скрытности и невидимости'
	ATSW_REDUCE_YOUR = 'уменьшит ваш '
	ATSW_SIZE = 'размер'
	ATSW_INCAPACITATE = 'обездвижить: '
	ATSW_DAMAGE_ABSORB_FOR = ' поглощ. урона на '
	ATSW_DISGUISE = 'маскировка: '
	ATSW_GORDOK_OGRE = 'Огр Гордока'
	ATSW_PIRATE_OR_NINJA = 'Пират или Ниндзя'
	ATSW_FLASK_OF_PETRIFICATION = '+неуязвимость, +бездействие'
	
	ATSW_DAMAGE_ON_BLOCK_FOR = 'урон при блоке на '
	ATSW_AND_ABOVE = ' и выше'
	
elseif Locale == 'zhCN' then
	ATSW_CLEAR 							= '清除'
	ATSW_CREATE 				    		= '制作'
	ATSW_STOP 					    		= '停止'
	ATSW_SORTBY 				    		= '排序方式:'
	ATSW_SORTBYCATEGORY 			= '分类'
	ATSW_SORTBYNAMES 				= '名称'
	ATSW_SORTBYDIFFICULTY			= '难度'
	ATSW_CUSTOMSORTING				= '自定义'
	ATSW_TASK 								= '队列'
	ATSW_SEARCHLABEL 					= '搜索'
	ATSW_ATTRIBUTES					= '属性'
	ATSW_REAGENTLIST1 				= '制作中:'
	ATSW_REAGENTLIST2				= '需要以下材料:'
	ATSW_REAGENTFRAMETITLE		= '你的制作清单中需要以下材料:'
	ATSW_REAGENTBUTTON			= '材料'
	ATSW_REAGENTFRAME_CH1		= '背包'
	ATSW_REAGENTFRAME_CH2		= '银行'
	ATSW_REAGENTFRAME_CH3		= '小号'
	ATSW_REAGENTFRAME_CH4		= '商人'
	ATSW_ALTLIST1						= '背包中'
	ATSW_ALTLIST2						= '银行中'
	ATSW_ANDMORE						= '更多...'

	ATSW_OPTIONS_TITLE				= 'Advanced Trade Skill Window 2 设置'
	ATSWOFTOTALDISPLAY_TEXT	= '显示总计数:'
	ATSWOFUCB_TEXT						= '统一展示'
	ATSWOFSCB_TEXT						= '分开展示'
	ATSWOFTOTALINCLUDE_TEXT	= '总计数包括:'
	ATSWOFADDONCOMPAT_TEXT	= '其它插件的兼容性'
	ATSWOFIB_TEXT 						= '银行'
	ATSWOFIA_TEXT 						= '小号'
	ATSWOFIM_TEXT 						= '商人'
	ATSWOFAB_TEXT 						= '商家自动购买\n|cffA0A0A0从商家自动购买与商家交谈时，自动为队列中的所有项目购买任何可能和必要的东西|r'
	ATSWOFTB_TEXT 						= '配方提示\n|cffA0A0A0当鼠标光标悬停在配方列表中的配方上时，显示工具提示|r'
	ATSWOFSLB_TEXT						= '拍卖行购物清单\n|cffA0A0A0在拍卖窗口下的任务列表中显示制作所有项目所需的材料列表|r'
	ATSWOF_INSTALLED					= '已安装'
	ATSWOF_ADDON						= '插件'
	ATSWOF_EFFECT						= '影响'
	ATSWOFALDESCRIPTION				= '提供配方和生产时间的生产水平'
	ATSWOFOKAY_TEXT					= '确定'

	ATSW_TOOLTIP_NECESSARY		= '所需材料:'
	ATSW_TOOLTIP_SKILLUPS			= '技能提升: '
	ATSW_TOOLTIP_POSSESS		    = '其它账号角色拥有'
	ATSW_TOOLTIP_BUYABLE 		    = '(可购买)'
	ATSW_TOOLTIP_INBAGS 		    = '背包'
	ATSW_TOOLTIP_INBANK 		    = '银行'
	ATSW_TOOLTIP_ONALTS 		    = '小号'
	ATSW_TOOLTIP_SAYREAGENTS	= '\n|cff1eff00Shift + 左键|r: |cffffffff|聊天(/s)说列出所需要的材料清单|r'
	ATSW_TOOLTIP_TO					= ' |cffffffffto|r '
	ATSW_TOOLTIP_YELL				= '叫声'
	ATSW_TOOLTIP_PARTY				= '派对'
	ATSW_TOOLTIP_GUILD				= '公会'
	ATSW_TOOLTIP_RAID				= '突袭'
	ATSW_TOOLTIP_ADDITEM		    = '\n|cff1eff00Shift + 左键|r: |cffffffff|添加所有项至任务制作清单中|r'
	ATSW_BUYBUTTON_TOPTEXT 	= '商人出售如下制作清单中所需的材料'
	ATSW_BUYBUTTON_TEXT			= '购买材料'
	ATSW_SHOPPINGLISTTITLE		= '当前制作清单中所有项目所需的材料清单:'

	ATSW_TOOLS 							= '工具:'
	ATSW_AMOUNT 						= '数量:'
	ATSW_ALL 								= '全部'
	ATSW_ENCHANT 						= '附魔'

	ATSW_CSBUTTON 						= '编辑'
	ATSWCS_TITLE 				    		= '编辑自定义排序'
	ATSWCS_TRADESKILLLISTTITLE	= '配方'
	ATSWCS_CATEGORYLISTTITLE	= '分类'
	ATSWCS_ADDCATEGORYLABEL	= '输入分类名称'
	ATSWCS_ADD 							= '添加'
	ATSWCS_RENAME						= '重命名'
	ATSWCS_DELETE						= '删除'
	ATSWCS_MOVEUP						= '向上移动'
	ATSWCS_MOVEDOWN				= '向下移动'
	ATSWCS_CATEGORYNAMETITLE 	= '名称:'
	ATSW_UNCATEGORIZED				= '未分类'

	BINDING_NAME_SHOWHIDE			= '显示 / 隐藏'

	ATSW_HELP_TITLE					= '搜索指令'
	ATSW_HELP_REAGENT				= ':reagent |cc材料名称|r|n:r |c材料名称|r'
	ATSW_HELP_REAGENT_DESC		= '- 列出包含该|c材料|r的配方'
	ATSW_HELP_LEVEL					= ':level |c等级|r|n:level |c1 - 10|r|n:level |c45+|r'
	ATSW_HELP_LEVEL_DESC			= '- 列出指定|c物品等级|r或|c等级范围|r的配方'
	ATSW_HELP_QUALITY				= ':quality |cQuality|r|n:q |cQuality|r|n:rarity |cQuality|r|n:r |cQuality|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r'
	ATSW_HELP_QUALITY_DESC		= '- 列出指定|c物品品质|r或|c品质范围|r的配方'
	ATSW_HELP_POSSIBLE				= ':possible |c可用次数|r|n:possible |c10+|r|n:possible |c1 - 40|r'
	ATSW_HELP_POSSIBLE_DESC		= '- 列出指定(背包)材料齐全并指定包含|c可用次数|r的制作配方'
	ATSW_HELP_POSSIBLE_TOTAL	= ':possibletotal |c可用次数|r'
	ATSW_HELP_POSSIBLE_TOTAL_DESC = '- 列出指定(背包、银行、小号、商人)材料齐全并包含|c可用次数|r的制作配方'
	ATSW_HELP_QNAMES					= '物品品质(Quality names):'
	ATSW_HELP_QNAMES_DESC		= '|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r'
	ATSW_HELP_QCOLORS				= '物品品质颜色(Quality colors):'
	ATSW_HELP_QCOLORS_DESC		= '|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r'
	
	----------------------------
	--  Attribute patterns   --
	--   简体中文翻译    --
	--     by Grok (xAI)      --
	----------------------------
	-- I personally don't speak chinese at all. If you speak chinese, have enough time and you want to correct this translation, it will be very good for the addon. It is easy to spot inconsistencies while playing (easy path) or modifiying the code to get information from atlas addon for every profession (hard path) or maybe you know your path (your path).
	
	ATSW_TO = ' 对 '
	ATSW_FOR = ' 为 '
	ATSW_OF = ' 的 '
	ATSW_AND = ' 和 '
	ATSW_PLUS_THREAT = '+威胁'
	ATSW_MINUS_THREAT = '-威胁'
	ATSW_CAST_TIME = '施法时间'
	ATSW_INC_HEAL = '受治疗'
	ATSW_STACK = '堆叠： '
	ATSW_CHARGES = ' 充能'

	ATSW_CHANCE_OF = ' 概率 '
	ATSW_CHANCE_FOR = '概率 '
	ATSW_RESIST = ' 抗性'
	ATSW_EVERY = ' 每 '
	ATSW_DAMAGE_TO = ' 伤害对 '
	ATSW_CHANCE_TO_REDUCE = ' 概率降低 '
	ATSW_DAMAGE_ON_HIT = ' 命中伤害 '
	ATSW_AND_DAMAGING = ' 和伤害 '
	ATSW_ON_HIT_FOR = ' 命中为 '
	ATSW_HEALING = ' 治疗'
	ATSW_SPELL_DAMAGE = ' 法术伤害'
	ATSW_DAMAGE = ' 伤害'
	ATSW_VAMPIRISM = ' 吸血'
	ATSW_HEALTH_AND = ' 生命和 '

	ATSW_ARMOR = ' 护甲'
	ATSW_STR = ' 力量'
	ATSW_AGI = ' 敏捷'
	ATSW_STA = ' 耐力'
	ATSW_INT = ' 智力'
	ATSW_SPI = ' 精神'
	ATSW_ALL_ATTRIBUTES = ' 全属性'
	ATSW_ALL_RESIST = ' 全抗性'
	ATSW_SLOTS = ' 插槽'

	ATSW_DAMAGE_ABSORB = ' 吸收伤害'
	ATSW_REFLECT = ' 反射'

	ATSW_FISHING = ' 钓鱼 '
	ATSW_DEFENSE = ' 防御'
	ATSW_DAMAGE_TAKEN = ' 受伤害'
	ATSW_DMG_TAKEN_CRITS_DOTS = ' 暴击和DoT伤害'
	ATSW_SPELL_POWER = ' 法术强度'
	ATSW_DAMAGE_FOR = ' 伤害为'
	ATSW_SPELL_DAMAGE_TO = ' 法术伤害对 '
	ATSW_BLOCK = ' 格挡'
	ATSW_PARRY = ' 招架'
	ATSW_DODGE = ' 闪避'
	ATSW_ATTACK_AND_CASTING_SPEED = ' 攻击和施法速度'

	ATSW_DAMAGE_ATTACKER_FOR = ' 对攻击者伤害为 '
	ATSW_LASTS = ' 持续 '
	ATSW_ON_MELEE = ' 近战攻击'

	ATSW_POISONS_OF = ' 毒药的 '
	ATSW_TARGETS_ALL_RESIST = ' 目标全抗'
	ATSW_NON_PHYSICAL_DEBUFF = '非物理减益每 '
	ATSW_SECONDS_FOR = ' 秒为 '
	ATSW_IMMUNITY_TO = '免疫 '
	ATSW_SHOWS = '显示 '
	ATSW_TO_CAST = ' 施法 '
	ATSW_REGEN_IF = ' %s 恢复若 '
	ATSW_CONTROL_MECHANICAL = '控制机械单位'
	ATSW_MELEE_SPELL_DAMAGE_AND = ' 近战和法术伤害和 '
	ATSW_MOVEMENT_FOR = ' 移动为 '

	ATSW_OF_TARGET = ' 目标的'
	ATSW_SCARES = '恐吓 '
	ATSW_ATTRACTS_MONSTERS = '吸引怪物为 '
	ATSW_ATTACK_SPEED_FOR = ' 攻击速度为 '
	ATSW_WILL_FIGHT = '为你战斗1.5分钟'
	ATSW_TO_OTHER = ' 对 '
	ATSW_HIT_FOR = ' 命中为'
	ATSW_SPELL_HIT_FOR = ' 法术命中为'
	ATSW_CRIT = ' 暴击'
	ATSW_CRIT_FOR = ' 暴击为'
	ATSW_SPELL_CRIT_FOR = ' 法术暴击为 '
	ATSW_WILL = '允许 '
	ATSW_DAMAGE_PER = ' 每伤害'
	ATSW_ATTACK_POWER_IN = ' 攻击强度在 '
	ATSW_ATTACK_POWER = ' 攻击强度'
	ATSW_RANGED_POWER = ' 远程强度'
	ATSW_ATTACK_POWER_AGAINST = ' 攻击强度对 '
	ATSW_ARMOR_IGNORE = ' 忽略护甲'
	ATSW_DPS = ' 每秒伤害'
	ATSW_HIT = ' 命中'
	ATSW_SPELL_HIT = ' 法术命中'
	ATSW_SPELL_CRIT = ' 法术暴击'
	ATSW_HEALTH_OVER = ' 生命恢复 '
	ATSW_HEALTH = ' 生命'
	ATSW_MANA = ' 魔法'
	ATSW_HEALTH_TO = ' 生命给 '

	ATSW_CD_REDUCED_BY = ' 冷却减少 '
	ATSW_COST_REDUCED_BY = ' 消耗减少 '
	ATSW_MANA_BURN_SILENCE = ' 烧魔法，沉默： '
	ATSW_DAMAGE_TO_YOU = ' 对你伤害'
	ATSW_RADIUS = '范围： '
	ATSW_CHANCE = ' 概率： '
	ATSW_CHANCE_OF_STUN = '眩晕概率： '
	ATSW_SECONDS = ' 秒'
	ATSW_STUN = '眩晕： '
	ATSW_DAMAGE_RECEIVED = ' 受伤害'
	ATSW_ATTACKER_OF_SPELL_FOR = ' 法术攻击者为 '
	ATSW_IF_DAMAGED_BY_SPELL = ' 若受法术伤害，护盾 '
	ATSW_OF_SAME_SCHOOL_FOR = ' 同系为 '
	ATSW_TO_RESTORE = ' 恢复 '
	ATSW_HEALTH_IF_DAMAGED = ' 生命若受伤害 '
	ATSW_OVER = ' 在 '
	ATSW_DAMAGE_TAKEN_BY = ' 受伤害从 '
	ATSW_CHANCE_TO = ' 概率 '
	ATSW_ATTACKER_OF_LEVEL = ' 最高等级攻击者 '
	ATSW_SPELL_POWER_FOR = ' 法术强度为 '
	ATSW_OF_LEVEL = ' 等级 '
	ATSW_AND_ABOVE = ' 及以上'
	ATSW_OTHER_DAMAGE = ' %s 伤害'
	ATSW_IMMUNE_TO = '免疫 '
	ATSW_DISARM = 'disarm'
	ATSW_SHIELD = ' 护盾 '
	ATSW_DISPEL = '驱散'
	ATSW_POLYMORPH = '变形术'
	ATSW_DAMAGE_OVER = ' 持续伤害 '
	ATSW_DAMAGE_AND = ' 伤害和 '
	ATSW_CRIT_FOR_PARTY = ' 队伍暴击为 '
	ATSW_FOR_PARTY = ' 为队伍'
	ATSW_HEALTH_ON_SPELL_HIT = ' 法术命中生命'
	ATSW_SPELL_DAMAGE_TAKEN_BY_TARGET = ' 目标受法术伤害'
	ATSW_CRIT_OF_NEXT_ATTACK = ' 下次攻击暴击在 '
	ATSW_MOVEMENT_AND = ' 移动和 '
	ATSW_ATTACK_SPEED_OF_TARGET = ' 目标攻击速度为 '
	ATSW_AND_DRAIN = ' 和抽取 '
	ATSW_MANA_ON_HIT = ' 命中魔法'
	ATSW_PROTECTION_FROM = '防护 '
	ATSW_TARGETS_STAT = ' 目标 %1$s'
	ATSW_MINUS_STEALTH_INVIS = '-潜行，-隐形'

	ATSW_COMPANION = '伙伴'
	ATSW_TOY = '玩具'
	ATSW_CHANCE_TO_RESURRECT = ' 复活玩家概率'
	ATSW_PORTAL_TO = '传送门至 '
	ATSW_TELEPORT_TO = '传送至 '
	ATSW_MIND_CONTROL_FOR = '精神控制为 '
	ATSW_STEALTH_INVISIBILITY_DETECTION = '侦测潜行和隐形'
	ATSW_REDUCE_YOUR = '缩小你的 '
	ATSW_SIZE = '尺寸'
	ATSW_INCAPACITATE = '瘫痪： '
	ATSW_DAMAGE_ABSORB_FOR = ' 吸收伤害为 '
	ATSW_DISGUISE = '伪装： '
	ATSW_GORDOK_OGRE = '戈多克食人魔'
	ATSW_PIRATE_OR_NINJA = '海盗或忍者'
	ATSW_FLASK_OF_PETRIFICATION = '+无敌，-行动能力'

	ATSW_DAMAGE_ON_BLOCK_FOR = '格挡伤害为 '
	ATSW_AND_ABOVE = ' 及以上'
	
else
	ATSW_CLEAR 							= 'Clear'
	ATSW_CREATE 							= 'Create'
	ATSW_STOP 								= 'Stop'
	ATSW_SORTBY 							= 'Sort by:'
	ATSW_SORTBYCATEGORY 			= 'Category'
	ATSW_SORTBYNAMES 				= 'Name'
	ATSW_SORTBYDIFFICULTY			= 'Difficulty'
	ATSW_CUSTOMSORTING 			= 'Custom'
	ATSW_TASK 								= 'Task'
	ATSW_SEARCHLABEL 					= 'Search'
	ATSW_ATTRIBUTES					= 'Attributes'
	ATSW_REAGENTLIST1 				= 'Crafting of'
	ATSW_REAGENTLIST2 				= 'require the following reagents:'
	ATSW_REAGENTFRAMETITLE 		= 'Your tasks require the following reagents:'
	ATSW_REAGENTBUTTON 			= 'Reagents'
	ATSW_REAGENTFRAME_CH1		= 'Bags'
	ATSW_REAGENTFRAME_CH2 		= 'Bank'
	ATSW_REAGENTFRAME_CH3 		= 'Alts'
	ATSW_REAGENTFRAME_CH4 		= 'Merchant'
	ATSW_ALTLIST1 						= 'in bags'
	ATSW_ALTLIST2 						= 'in bank'
	ATSW_ANDMORE						= 'and more...'
	
	ATSW_OPTIONS_TITLE 				= 'Advanced Trade Skill Window 2 Configuration'
	ATSWOFTOTALDISPLAY_TEXT	= 'Total count is displayed:'
	ATSWOFUCB_TEXT						= 'Unified'
	ATSWOFSCB_TEXT 					= 'Separated'
	ATSWOFTOTALINCLUDE_TEXT 	= 'Total count include:'
	ATSWOFADDONCOMPAT_TEXT	= 'Compatibility with add-ons'
	ATSWOFIB_TEXT 						= 'Bank'
	ATSWOFIA_TEXT 						= 'Alternative characters'
	ATSWOFIM_TEXT 						= 'Merchant'
	ATSWOFAB_TEXT 						= 'Autobuy from merchant\n|cffA0A0A0Automatically buy anything possible and necessary for all items \nin the task list when speaking to merchants|r'
	ATSWOFTB_TEXT 						= 'Recipe tooltip\n|cffA0A0A0Display a tooltip when a mouse cursor is hovering over a recipe \nin the recipe list|r'
	ATSWOFSLB_TEXT 					= 'Auction house shopping list\n|cffA0A0A0Display a list of items that are required for crafting all items \nin the task list under auction window|r'
	ATSWOF_INSTALLED					= 'Installed'
	ATSWOF_ADDON						= 'Add-on'
	ATSWOF_EFFECT						= 'Effect'
	ATSWOFALDESCRIPTION				= 'Provides crafting skill-up levels\nand crafting time'
	ATSWOFOKAY_TEXT					= 'OKAY'
	
	ATSW_TOOLTIP_NECESSARY 		= 'Required reagents:'
	ATSW_TOOLTIP_SKILLUPS			= 'Skill-ups: '
	ATSW_TOOLTIP_POSSESS			=	'These characters possess'
	ATSW_TOOLTIP_BUYABLE 			= '(buyable)'
	ATSW_TOOLTIP_INBAGS 			= 'Bags'
	ATSW_TOOLTIP_INBANK 			= 'Bank'
	ATSW_TOOLTIP_ONALTS 			= 'Alts'
	ATSW_TOOLTIP_SAYREAGENTS	= '\n|cff1eff00Shift + Left Click|r: |cffffffffSay reagents required to craft the item|r'
	ATSW_TOOLTIP_TO					= ' |cffffffffto|r '
	ATSW_TOOLTIP_YELL				= 'yell'
	ATSW_TOOLTIP_PARTY				= 'party'
	ATSW_TOOLTIP_GUILD				= 'guild'
	ATSW_TOOLTIP_RAID				= 'raid'
	ATSW_TOOLTIP_ADDITEM			= '\n|cff1eff00Shift + Left Click|r: |cffffffffAdd all items to tasks|r'
	ATSW_BUYBUTTON_TOPTEXT 	= 'This merchant sells reagents that are necessary for tasks for'
	ATSW_BUYBUTTON_TEXT 			= 'Buy reagents'
	ATSW_SHOPPINGLISTTITLE 		= 'Reagents required to create all items in the task list:'
	
	ATSW_TOOLS 							= 'Tools:'
	ATSW_AMOUNT 						= 'Amount:'
	ATSW_ALL 								= 'All'
	ATSW_ENCHANT 						= 'Enchant'
	
	ATSW_CSBUTTON 						= 'Editor'
	ATSWCS_TITLE 							= 'Custom Sorting Editor'
	ATSWCS_TRADESKILLLISTTITLE 	= 'Recipes'
	ATSWCS_CATEGORYLISTTITLE 	= 'Categories'
	ATSWCS_ADDCATEGORYLABEL 	= 'Enter category name'
	ATSWCS_ADD 							= 'Add'
	ATSWCS_RENAME						= 'Rename'
	ATSWCS_DELETE						= 'Delete'
	ATSWCS_MOVEUP						= 'Move up'
	ATSWCS_MOVEDOWN				= 'Move down'
	ATSWCS_CATEGORYNAMETITLE 	= 'Name:'
	ATSW_UNCATEGORIZED 			= 'Uncategorized'
	
	BINDING_NAME_SHOWHIDE			=	'Show / Hide'
	
	ATSW_HELP_TITLE					= 'Search commands'
	ATSW_HELP_REAGENT				= ':reagent |cReagent|r|n:r |cReagent|r'
	ATSW_HELP_REAGENT_DESC		= '- show recipes that require |cReagent|r to craft'
	ATSW_HELP_LEVEL					= ':level |cLevel|r|n:level |c1 - 10|r|n:level |c45+|r'
	ATSW_HELP_LEVEL_DESC			= '- show recipes that produce items of |cLevel|r level'
	ATSW_HELP_QUALITY				= ':quality |cQuality|r|n:q |cQuality|r|n:rarity |cQuality|r|n:r |cQuality|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r'
	ATSW_HELP_QUALITY_DESC		= '- show recipes that produce items of |cQuality|r quality'
	ATSW_HELP_POSSIBLE				= ':possible |cAmount|r|n:possible |c10+|r|n:possible |c1 - 40|r'
	ATSW_HELP_POSSIBLE_DESC		= '- show recipes that can be crafted |cAmount|r times using materials in your bags'
	ATSW_HELP_POSSIBLE_TOTAL	= ':possibletotal |cAmount|r'
	ATSW_HELP_POSSIBLE_TOTAL_DESC = '- show recipes that can be crafted |cAmount|r times using materials in your bags and locations specified in options menu (Bank, Alternative characters or Merchant)'
	ATSW_HELP_QNAMES					= 'Quality names:'
	ATSW_HELP_QNAMES_DESC		= '|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r'
	ATSW_HELP_QCOLORS				= 'Quality colors:'
	ATSW_HELP_QCOLORS_DESC		= '|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r'

	----------------------------
	--  Attribute patterns   --
	--     by Grok (xAI)      --
	----------------------------
	
	ATSW_TO = ' for '
	ATSW_FOR = ' for '
	ATSW_OF = ' of '
	ATSW_AND = ' and '
	ATSW_PLUS_THREAT = '+threat'
	ATSW_MINUS_THREAT = '-threat'
	ATSW_CAST_TIME = 'cast time'
	ATSW_INC_HEAL = 'inc. heal'
	ATSW_STACK = 'stack: '
	ATSW_CHARGES = ' charges'
	
	ATSW_CHANCE_OF = ' chance of '
	ATSW_CHANCE_FOR = 'chance for '
	ATSW_RESIST = ' resist'
	ATSW_EVERY = ' every '
	ATSW_DAMAGE_TO = ' damage to '
	ATSW_CHANCE_TO_REDUCE = ' chance to reduce target\'s '
	ATSW_DAMAGE_ON_HIT = ' damage on hit '
	ATSW_AND_DAMAGING = ' and damaging'
	ATSW_ON_HIT_FOR = ' on hit for '
	ATSW_HEALING = ' healing'
	ATSW_SPELL_DAMAGE = ' spell damage'
	ATSW_DAMAGE = ' damage'
	ATSW_VAMPIRISM = 'vampirism'
	ATSW_HEALTH_AND = ' health and '
	
	ATSW_ARMOR = ' armor'
	ATSW_STR = ' str.'
	ATSW_AGI = ' agi.'
	ATSW_STA = ' sta.'
	ATSW_INT = ' int.'
	ATSW_SPI = ' spi.'
	ATSW_ALL_ATTRIBUTES = ' all attributes'
	ATSW_ALL_RESIST = ' all resist'
	ATSW_SLOTS = ' slots'
	
	ATSW_DAMAGE_ABSORB = ' damage absorb'
	ATSW_REFLECT = ' reflect'
	
	ATSW_FISHING = ' fishing '
	ATSW_DEFENSE = ' defense'
	ATSW_DAMAGE_TAKEN = ' damage taken'
	ATSW_DMG_TAKEN_CRITS_DOTS = ' dmg taken from crits and DoTs.'
	ATSW_SPELL_POWER = ' spell power'
	ATSW_DAMAGE_FOR = ' damage for'
	ATSW_SPELL_DAMAGE_TO = ' spell damage to '
	ATSW_BLOCK = ' block'
	ATSW_PARRY = ' parry'
	ATSW_DODGE = ' dodge'
	ATSW_ATTACK_AND_CASTING_SPEED = ' attack and casting speed'
	
	ATSW_DAMAGE_ATTACKER_FOR = ' damage against the attacker for '
	ATSW_LASTS = ' Lasts '
	ATSW_ON_MELEE = ' on melee attack'
	
	ATSW_POISONS_OF = ' poisons of '
	ATSW_TARGETS_ALL_RESIST = ' target\'s all resist'
	ATSW_NON_PHYSICAL_DEBUFF = 'non-physical debuff every '
	ATSW_SECONDS_FOR = ' sec. for '
	ATSW_IMMUNITY_TO = 'immunity to '
	ATSW_SHOWS = 'shows '
	ATSW_TO_CAST = ' to cast '
	ATSW_REGEN_IF = ' %s regen if '
	ATSW_CONTROL_MECHANICAL = 'control of a mechanical unit'
	ATSW_MELEE_SPELL_DAMAGE_AND = ' melee and spell damage and '
	ATSW_MOVEMENT_FOR = ' movement for '
	
	ATSW_OF_TARGET = ' of target'
	ATSW_SCARES = 'scares '
	ATSW_ATTRACTS_MONSTERS = 'Attracts monsters for '
	ATSW_ATTACK_SPEED_FOR = ' attack speed for '
	ATSW_WILL_FIGHT = 'will fight for you for 1.5 min.'
	ATSW_TO_OTHER = ' to '
	ATSW_HIT_FOR = ' hit for'
	ATSW_SPELL_HIT_FOR = ' spell hit for'
	ATSW_CRIT = ' crit.'
	ATSW_CRIT_FOR = ' crit. for'
	ATSW_SPELL_CRIT_FOR = ' spell crit. for '
	ATSW_WILL = 'will '
	ATSW_DAMAGE_PER = ' damage per'
	ATSW_ATTACK_POWER_IN = ' attack power in '
	ATSW_ATTACK_POWER = ' attack power'
	ATSW_RANGED_POWER = ' ranged power'
	ATSW_ATTACK_POWER_AGAINST = ' attack power against '
	ATSW_ARMOR_IGNORE = ' armor ignore'
	ATSW_DPS = ' dps'
	ATSW_HIT = ' hit'
	ATSW_SPELL_HIT = ' spell hit'
	ATSW_SPELL_CRIT = ' spell crit.'
	ATSW_HEALTH_OVER = ' health over '
	ATSW_HEALTH = ' health'
	ATSW_MANA = ' mana'
	ATSW_HEALTH_TO = ' health to '
	
	ATSW_CD_REDUCED_BY = ' cd reduced by '
	ATSW_COST_REDUCED_BY = ' cost reduced by '
	ATSW_MANA_BURN_SILENCE = ' mana burn, silence: '
	ATSW_DAMAGE_TO_YOU = ' damage to you'
	ATSW_RADIUS = 'radius:'
	ATSW_CHANCE = ' chance: '
	ATSW_CHANCE_OF_STUN = 'chance of stun: '
	ATSW_SECONDS = ' sec.'
	ATSW_STUN = 'stun: '
	ATSW_DAMAGE_RECEIVED = ' damage received'
	ATSW_ATTACKER_OF_SPELL_FOR = ' attacker of spell for '
	ATSW_IF_DAMAGED_BY_SPELL = ' if damaged by spell to get a shield of '
	ATSW_OF_SAME_SCHOOL_FOR = ' of same school for '
	ATSW_TO_RESTORE = ' to restore '
	ATSW_HEALTH_IF_DAMAGED = ' health if damaged '
	ATSW_OVER = ' over '
	ATSW_DAMAGE_TAKEN_BY = ' damage taken by '
	ATSW_CHANCE_TO = ' chance to '
	ATSW_ATTACKER_OF_LEVEL = ' attacker of max. level '
	ATSW_SPELL_POWER_FOR = ' spell power for '
	ATSW_OF_LEVEL = ' of level '
	ATSW_AND_ABOVE = ' and above'
	ATSW_OTHER_DAMAGE = ' %s damage'
	ATSW_IMMUNE_TO = 'immune to '
	ATSW_DISARM = 'disarm'
	ATSW_SHIELD = ' shield '
	ATSW_DISPEL = 'dispel'
	ATSW_POLYMORPH = 'polymorph'
	ATSW_DAMAGE_OVER = ' damage over '
	ATSW_DAMAGE_AND = ' damage and '
	ATSW_CRIT_FOR_PARTY = ' crit. for party for '
	ATSW_FOR_PARTY = ' for party'
	ATSW_HEALTH_ON_SPELL_HIT = ' health on spell hit'
	ATSW_SPELL_DAMAGE_TAKEN_BY_TARGET = ' spell damage taken by target'
	ATSW_CRIT_OF_NEXT_ATTACK = ' crit. of next attack within '
	ATSW_MOVEMENT_AND = ' movement and '
	ATSW_ATTACK_SPEED_OF_TARGET = ' attack speed of target for '
	ATSW_AND_DRAIN = ' and drain target\'s '
	ATSW_MANA_ON_HIT = ' mana on hit'
	ATSW_PROTECTION_FROM = 'protection from '
	ATSW_TARGETS_STAT = ' target\'s %1$s'
	ATSW_MINUS_STEALTH_INVIS = '-stealth, -invisibility'
	
	ATSW_COMPANION = 'companion'
	ATSW_TOY = 'toy'
	ATSW_CHANCE_TO_RESURRECT = ' chance to resurrect a player'
	ATSW_PORTAL_TO = 'portal to '
	ATSW_TELEPORT_TO = 'teleport to '
	ATSW_MIND_CONTROL_FOR = 'mind control for '
	ATSW_STEALTH_INVISIBILITY_DETECTION = 'stealth and invisibility detection'
	ATSW_REDUCE_YOUR = 'reduce your '
	ATSW_SIZE = 'size'
	ATSW_INCAPACITATE = 'incapacitate: '
	ATSW_DAMAGE_ABSORB_FOR = ' damage absorb for '
	ATSW_DISGUISE = 'disguise: '
	ATSW_GORDOK_OGRE = 'Gordok Ogre'
	ATSW_PIRATE_OR_NINJA = 'Pirate or Ninja'
	ATSW_FLASK_OF_PETRIFICATION = '+invincibility, -ability to act'
	
	ATSW_DAMAGE_ON_BLOCK_FOR = 'damage on block for '
	ATSW_AND_ABOVE = ' and above'
end
