-- Language file

-- German and English Language by Rene Schneider, Alexander Sheloknev
-- Русский язык доработал Александр Шелохнёв
-- French language is made by Nilyn (EU Dalaran Alliance Server)
-- El idioma español está compuesto por Jsr1976-Fili

ATSW_VERSION 							= "Advanced Trade Skill Window ".. GetAddOnMetadata("AdvancedTradeSkillWindow", "Version")
BINDING_HEADER_ATSW					= "Advanced Trade Skill Window"

if GetLocale()=="deDE" then
	ATSW_CLEAR 							= "Klar"
	ATSW_CREATE 							= "Schaffen"
	ATSW_STOP 								= "Halt"
	ATSW_SORTBY 							= "Sortieren:"
	ATSW_SORTBYCATEGORY 			= "Kategorie"
	ATSW_SORTBYNAMES 				= "Name"
	ATSW_SORTBYDIFFICULTY 			= "Schwierigkeit"
	ATSW_CUSTOMSORTING 			= "Brauch"
	ATSW_TASK 								= "Task"
	ATSW_SEARCHLABEL 					= "Suche"
	ATSW_REAGENTLIST1 				= "Zur Herstellung von"
	ATSW_REAGENTLIST2 				= "werden folgende Reagenzien benötigt:"
	ATSW_REAGENTFRAMETITLE 		= "Ihre Aufgaben erfordern die folgenden Reagenzien:"
	ATSW_REAGENTBUTTON 			= "Reagenzien"
	ATSW_REAGENTFRAME_CH1 		= "Taschen"
	ATSW_REAGENTFRAME_CH2 		= "Bank"
	ATSW_REAGENTFRAME_CH3 		= "Twink"
	ATSW_REAGENTFRAME_CH4 		= "Händler"
	ATSW_ALTLIST1 						= "in Taschen"
	ATSW_ALTLIST2 						= "auf der Bank"
	ATSW_ANDMORE						= "und mehr..."
	
	ATSW_OPTIONS_TITLE 				= "Advanced Trade Skill Window optionen"
	ATSWOFTOTALDISPLAY_TEXT 	= "Gesamtzahl wird angezeigt:"
	ATSWOFUCB_TEXT 					= "Unified"
	ATSWOFSCB_TEXT 					= "Separated"
	ATSWOFTOTALINCLUDE_TEXT 	= "Die Gesamtzahl umfasst:"
	ATSWOFIB_TEXT 						= "Bank"
	ATSWOFIA_TEXT 						= "Alternative Zeichen"
	ATSWOFIM_TEXT 						= "Händler"
	ATSWOFAB_TEXT 						= "Autokauf vom Händler\n|cff808080Kaufen Sie automatisch alles Mögliche und Notwendige für alle Artikel \nin der Aufgabenliste, wenn Sie mit Händlern sprechen|r"
	ATSWOFTB_TEXT 						= "Kurzinfo zum Rezept\n|cff808080Zeigen Sie einen Tooltip an, wenn ein Mauszeiger über einem Rezept \nin der Rezeptliste schwebt|r"
	ATSWOFSLB_TEXT 					= "Einkaufsliste des Auktionshauses\n|cff808080Zeigen Sie eine Liste der Gegenstände an, die zum Herstellen aller Gegenstände \nin der Aufgabenliste unter dem Auktionsfenster erforderlich sind|r"
	
	ATSW_TOOLTIP_NECESSARY 		= "Benötigte reagenzien:"
	ATSW_TOOLTIP_POSESS			=	"Diese charaktere besitzen"
	ATSW_TOOLTIP_BUYABLE 			= "(käuflich)"
	ATSW_TOOLTIP_INBAGS 			= "Taschen:"
	ATSW_TOOLTIP_INBANK 			= "Bank:"
	ATSW_TOOLTIP_ONALTS 			= "Twinks:"
	ATSW_TOOLTIP_SAYREAGENTS	= "\n|cff1eff00Umschalt + Linksklick|r: |cffffffffFügen Sie alle Reagenzien zum Chat hinzu|r"
	ATSW_TOOLTIP_ADDITEM			= "\n|cff1eff00Umschalt + Linksklick|r: |cffffffffAlle Elemente zu Aufgaben hinzufügen|r"
	ATSW_BUYBUTTON_TOPTEXT 	= "Dieser Händler verkauft Reagenzien, die für Aufgaben benötigt werden, für"
	ATSW_BUYBUTTON_TEXT 			= "Reagenzien kaufen"
	ATSW_SHOPPINGLISTTITLE 		= "Erforderliche Reagenzien zum Erstellen aller Elemente in der Aufgabenliste:"
	
	ATSW_TOOLS 							= "Werkzeug:"
	ATSW_AMOUNT 						= "Menge:"
	ATSW_ALL 								= "Alle"
	ATSW_ENCHANT 						= "Verzaubern"
	
	ATSW_CSBUTTON 						= "Editor"
	ATSWCS_TITLE 							= "Benutzerdefinierter Sortiereditor"
	ATSWCS_TRADESKILLISTTITLE 	= "Rezepturen"
	ATSWCS_CATEGORYLISTTITLE 	= "Kategorien"
	ATSWCS_ADDCATEGORYLABEL 	= "Geben Sie den Kategorienamen ein"
	ATSWCS_ADD 							= "Addieren"
	ATSWCS_CATEGORYNAMETITLE	= "Name:"
	ATSW_UNCATEGORIZED 			= "Unkategorisiert"
	
	BINDING_NAME_SHOWHIDE			=	"Anzeigen / Ausblenden"
	
	ATSW_HELP_TITLE					= "Suchbefehle"
	ATSW_HELP_REAGENT				= ":reagent |cReagens|r|n:r |cReagens|r"
	ATSW_HELP_REAGENT_DESC		= "- rezepte anzeigen, für deren Herstellung |cReagens|r erforderlich ist"
	ATSW_HELP_LEVEL					= ":level |cEben|r|n:level |c1 - 10|r|n:level |c45+|r"
	ATSW_HELP_LEVEL_DESC			= "- zeigt Rezepte, die Gegenstände der Stufe |cEben|r produzieren"
	ATSW_HELP_QUALITY				= ":quality |cQualität|r|n:q |cQualität|r|n:rarity |cQualität|r|n:r |cQualität|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r"
	ATSW_HELP_QUALITY_DESC		= "- zeigt Rezepte, die Gegenstände von |cQualität|r-Qualität herstellen"
	ATSW_HELP_POSSIBLE				= ":possible |cMenge|r|n:possible |c10+|r|n:possible |c1 - 40|r"
	ATSW_HELP_POSSIBLE_DESC		= "- zeigt Rezepte, die |cMenge|r-mal mit Materialien in euren Taschen hergestellt werden können"
	ATSW_HELP_POSSIBLE_TOTAL	= ":possibletotal |cMenge|r"
	ATSW_HELP_POSSIBLE_TOTAL_DESC = "- zeigt Rezepte an, die |cMenge|r-mal mit Materialien in deinen Taschen und Orten hergestellt werden können, die im Optionsmenü angegeben sind (Bank, alternative Charaktere oder Händler)"
	ATSW_HELP_QNAMES					= "Qualitätsnamen:"
	ATSW_HELP_QNAMES_DESC		= "|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r"
	ATSW_HELP_QCOLORS				= "Qualitätsfarben:"
	ATSW_HELP_QCOLORS_DESC		= "|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r"
elseif GetLocale()=="frFR" then
	ATSW_CLEAR 							= "Nettoyer"
	ATSW_CREATE 							= "Créer"
	ATSW_STOP 								= "Arrêt"
	ATSW_SORTBY 							= "Trier par:"
	ATSW_SORTBYCATEGORY 			= "Catégorie"
	ATSW_SORTBYDIFFICULTY 			= "Difficulté"
	ATSW_SORTBYNAMES 				= "Nom"
	ATSW_CUSTOMSORTING 			= "Personnalisé"
	ATSW_TASK 								= "Tâche"
	ATSW_SEARCHLABEL 					= "Chercher"
	ATSW_REAGENTLIST1 				= "Pour produir"
	ATSW_REAGENTLIST2 				= "les réactifs suivants sont nécessaire:"
	ATSW_REAGENTFRAMETITLE 		= "Vos tâches nécessitent les réactifs suivants:"
	ATSW_REAGENTBUTTON 			= "Réactifs"
	ATSW_REAGENTFRAME_CH1 		= "Sacs"
	ATSW_REAGENTFRAME_CH2 		= "Banque"
	ATSW_REAGENTFRAME_CH3 		= "Alts"
	ATSW_REAGENTFRAME_CH4 		= "Marchand"
	ATSW_ALTLIST1 						= "dans des sacs"
	ATSW_ALTLIST2 						= "dans la banque"
	ATSW_ANDMORE						= "et plus..."
	
	ATSW_OPTIONS_TITLE 				= "Options Advanced Trade Skill Window"
	ATSWOFTOTALDISPLAY_TEXT 	= "Le nombre total est affiché :"
	ATSWOFUCB_TEXT 					= "Unifié"
	ATSWOFSCB_TEXT 					= "Séparé"
	ATSWOFTOTALINCLUDE_TEXT 	= "Le nombre total comprend :"
	ATSWOFIB_TEXT 						= "La banque"
	ATSWOFIA_TEXT 						= "Les personnages alternatifs"
	ATSWOFIM_TEXT 						= "Le marchand"
	ATSWOFAB_TEXT 						= "Achat automatique auprès d'un marchand\n|cff808080Achetez automatiquement tout ce qui est possible et nécessaire \npour tous les articles de la liste des tâches lorsque vous parlez aux marchands|r"
	ATSWOFTB_TEXT 						= "Info-bulle de la recette\n|cff808080Afficher une info-bulle lorsque le curseur de la souris survole \nune recette dans la liste des recettes|r"
	ATSWOFSLB_TEXT 					= "Liste de courses de la maison de vente aux enchères\n|cff808080Afficher une liste des objets nécessaires à la fabrication de tous \nles objets de la liste des tâches sous la fenêtre d'enchères|r"
	
	ATSW_TOOLTIP_NECESSARY 		= "Réactifs nécessaires:"
	ATSW_TOOLTIP_POSESS			=	"Ces personnages possèdent"
	ATSW_TOOLTIP_BUYABLE 			= "(Achetable)"
	ATSW_TOOLTIP_INBAGS 			= "Sacs:"
	ATSW_TOOLTIP_INBANK 			= "Banque:"
	ATSW_TOOLTIP_ONALTS 			= "Alts:"
	ATSW_TOOLTIP_SAYREAGENTS	= "\n|cff1eff00Maj. + Clic gauche|r: |cffffffffAjouter tous les réactifs dans le chat|r"
	ATSW_TOOLTIP_ADDITEM			= "\n|cff1eff00Maj. + Clic gauche|r: |cffffffffAjouter tous les éléments aux tâches|r"
	ATSW_BUYBUTTON_TOPTEXT 	= "Ce marchand vend des réactifs nécessaires aux tâches de"
	ATSW_BUYBUTTON_TEXT 			= "Acheter des réactifs"
	ATSW_SHOPPINGLISTTITLE 		= "Réactifs requis pour créer tous les éléments de la liste des tâches:"
	
	ATSW_TOOLS 							= "Outils:"
	ATSW_AMOUNT 						= "Montant:"
	ATSW_ALL 								= "Tout"
	ATSW_ENCHANT 						= "Enchanter"
	
	ATSW_CSBUTTON 						= "Editeur"
	ATSWCS_TITLE 							= "Editeur de Classement personnel"
	ATSWCS_TRADESKILLISTTITLE 	= "Recettes"
	ATSWCS_CATEGORYLISTTITLE 	= "Catégories"
	ATSWCS_ADDCATEGORYLABEL 	= "Saisissez le nom de la catégorie"
	ATSWCS_ADD 							= "Ajouter"
	ATSWCS_CATEGORYNAMETITLE 	= "Nom:"
	ATSW_UNCATEGORIZED 			= "Non classé"
	
	BINDING_NAME_SHOWHIDE			=	"Afficher / Masquer"
	
	ATSW_HELP_TITLE					= "Commandes de recherche"
	ATSW_HELP_REAGENT				= ":reagent |cRéactif|r|n:r |cRéactif|r"
	ATSW_HELP_REAGENT_DESC		= "- afficher les recettes qui nécessitent |cRéactif|r pour être fabriquées"
	ATSW_HELP_LEVEL					= ":level |cNiveau|r|n:level |c1 - 10|r|n:level |c45+|r"
	ATSW_HELP_LEVEL_DESC			= "- afficher des recettes qui produisent des objets de niveau |cNiveau|r"
	ATSW_HELP_QUALITY				= ":quality |cQualité|r|n:q |cQualité|r|n:rarity |cQualité|r|n:r |cQualité|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r"
	ATSW_HELP_QUALITY_DESC		= "- montrer des recettes qui produisent des articles de qualité |cQualité|r"
	ATSW_HELP_POSSIBLE				= ":possible |cNombre|r|n:possible |c10+|r|n:possible |c1 - 40|r"
	ATSW_HELP_POSSIBLE_DESC		= "- montrer des recettes qui peuvent être fabriquées |cNombre|r de fois en utilisant des matériaux dans vos sacs"
	ATSW_HELP_POSSIBLE_TOTAL	= ":possibletotal |cNombre|r"
	ATSW_HELP_POSSIBLE_TOTAL_DESC = "- afficher les recettes qui peuvent être fabriquées |cNombre|r de fois en utilisant les matériaux dans vos sacs et les emplacements spécifiés dans le menu des options (Banque, Personnages alternatifs ou Marchand)"
	ATSW_HELP_QNAMES					= "Noms de qualité:"
	ATSW_HELP_QNAMES_DESC		= "|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r"
	ATSW_HELP_QCOLORS				= "Couleurs de qualité:"
	ATSW_HELP_QCOLORS_DESC		= "|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r"
	
elseif GetLocale()=="esES" then
	ATSW_CLEAR 							= "Claro"
	ATSW_CREATE 							= "Crear"
	ATSW_STOP 								= "Cancelar"
	ATSW_SORTBY 							= "Ordenar por:"
	ATSW_SORTBYCATEGORY 			= "Categoría"
	ATSW_SORTBYDIFFICULTY 			= "Dificultad"
	ATSW_SORTBYNAMES 				= "Nombre"
	ATSW_CUSTOMSORTING 			= "Personalizado"
	ATSW_TASK 								= "Tarea"
	ATSW_SEARCHLABEL 					= "Buscar"
	ATSW_REAGENTLIST1 				= "La elaboración"
	ATSW_REAGENTLIST2 				= "requiere los siguientes reactivos:"
	ATSW_REAGENTFRAMETITLE 		= "Sus tareas requieren los siguientes reactivos:"
	ATSW_REAGENTBUTTON 			= "Reactivos"
	ATSW_REAGENTFRAME_CH1 		= "Bolsas"
	ATSW_REAGENTFRAME_CH2 		= "Banco"
	ATSW_REAGENTFRAME_CH3 		= "Alt"
	ATSW_REAGENTFRAME_CH4 		= "Mercader"
	ATSW_ALTLIST1 						= "en bolsas"
	ATSW_ALTLIST2 						= "en el banco"
	ATSW_ANDMORE						= "y más..."
	
	ATSW_OPTIONS_TITLE 				= "Advanced Trade Skill Window optcones"
	ATSWOFTOTALDISPLAY_TEXT 	= "Se muestra el conteo total:"
	ATSWOFUCB_TEXT 					= "Unificado"
	ATSWOFSCB_TEXT 					= "Separado"
	ATSWOFTOTALINCLUDE_TEXT 	= "El recuento total incluye:"
	ATSWOFIB_TEXT 						= "Banco"
	ATSWOFIA_TEXT 						= "Personajes alternativos"
	ATSWOFIM_TEXT 						= "Mercader"
	ATSWOFAB_TEXT 						= "Autocompra del mercader\n|cff808080Compre automáticamente todo lo posible y necesario para todos \nlos elementos de la lista de tareas cuando hable con los comerciantes|r"
	ATSWOFTB_TEXT 						= "Información de la receta\n|cff808080Muestre una información sobre herramientas cuando el cursor del mouse \nse desplace sobre una receta en la lista de recetas|r"
	ATSWOFSLB_TEXT 					= "Lista de compras de la casa de subastas\n|cff808080Muestre una lista de artículos que se requieren para fabricar todos \nlos artículos en la lista de tareas en la ventana de subasta|r"

	ATSW_TOOLTIP_NECESSARY 		= "Reactivos necesarios:"
	ATSW_TOOLTIP_POSESS			=	"Estos personajes poseen"
	ATSW_TOOLTIP_BUYABLE 			= "(adquirible)"
	ATSW_TOOLTIP_INBAGS 			= "Bolsas:"
	ATSW_TOOLTIP_INBANK 			= "Banco:"
	ATSW_TOOLTIP_ONALTS 			= "Alts:"
	ATSW_TOOLTIP_SAYREAGENTS	= "\n|cff1eff00Mayús + Clic izquierdo|r: |cffffffffAgregue todos los reactivos al chat|r"
	ATSW_TOOLTIP_ADDITEM			= "\n|cff1eff00Mayús + Clic izquierdo|r: |cffffffffAgregar todos los elementos a las tareas|r"
	ATSW_BUYBUTTON_TOPTEXT 	= "Este mercader vende reactivos que son necesarios para las tareas de"
	ATSW_BUYBUTTON_TEXT 			= "Comprar reactivos"
	ATSW_SHOPPINGLISTTITLE 		= "Lista de compra que necesitas para producir los objetos de la cola:"
	
	ATSW_TOOLS 							= "Instrumentos:"
	ATSW_AMOUNT 						= "Monto:"
	ATSW_ALL 								= "Todos"
	ATSW_ENCHANT 						= "Encantar"
	
	ATSW_CSBUTTON 						= "Editor"
	ATSWCS_TITLE 							= "Editor de clasificación personalizado"
	ATSWCS_TRADESKILLISTTITLE 	= "Recetas"
	ATSWCS_CATEGORYLISTTITLE 	= "Categorías"
	ATSWCS_ADDCATEGORYLABEL 	= "Introduce el nombre de la categoría"
	ATSWCS_ADD 							= "Agregar"
	ATSWCS_CATEGORYNAMETITLE 	= "Nombre:"
	ATSW_UNCATEGORIZED 			= "Sin Categoria"
	
	BINDING_NAME_SHOWHIDE			=	"Mostrar / Ocultar"
	
	ATSW_HELP_TITLE					= "Comandos de búsqueda"
	ATSW_HELP_REAGENT				= ":reagent |cReactivo|r|n:r |cReactivo|r"
	ATSW_HELP_REAGENT_DESC		= "- mostrar recetas que requieren |cReactivo|r para elaborar"
	ATSW_HELP_LEVEL					= ":level |cNivel|r|n:level |c1 - 10|r|n:level |c45+|r"
	ATSW_HELP_LEVEL_DESC			= "- mostrar recetas que producen artículos de nivel |cNivel|r"
	ATSW_HELP_QUALITY				= ":quality |cCalidad|r|n:q |cCalidad|r|n:rarity |cCalidad|r|n:r |cCalidad|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r"
	ATSW_HELP_QUALITY_DESC		= "- mostrar recetas que producen artículos de |cCalidad|r calidad"
	ATSW_HELP_POSSIBLE				= ":possible |cMonto|r|n:possible |c10+|r|n:possible |c1 - 40|r"
	ATSW_HELP_POSSIBLE_DESC		= "- muestra recetas que se pueden fabricar |cMonto|r veces usando materiales en tus bolsas"
	ATSW_HELP_POSSIBLE_TOTAL	= ":possibletotal |cMonto|r"
	ATSW_HELP_POSSIBLE_TOTAL_DESC = "muestre recetas que se pueden fabricar |cMonto|r veces usando materiales en sus bolsas y ubicaciones especificadas en el menú de opciones (Banco, Personajes alternativos o Comerciante)"
	ATSW_HELP_QNAMES					= "Nombres de calidad:"
	ATSW_HELP_QNAMES_DESC		= "|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r"
	ATSW_HELP_QCOLORS				= "Colores de calidad:"
	ATSW_HELP_QCOLORS_DESC		= "|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r"
	
elseif GetLocale()=="ruRU" then
	ATSW_CLEAR 							= "Очистить"
	ATSW_CREATE 							= "Создать"
	ATSW_STOP 								= "Стоп"
	ATSW_SORTBY 							= "Сортировка:"
	ATSW_SORTBYCATEGORY 			= "Категория"
	ATSW_SORTBYNAMES 				= "Имя"
	ATSW_SORTBYDIFFICULTY 			= "Навык"
	ATSW_CUSTOMSORTING 			= "Своя"
	ATSW_TASK 								= "Задача"
	ATSW_SEARCHLABEL 					= "Поиск"
	ATSW_REAGENTLIST1 				= "Создание"
	ATSW_REAGENTLIST2 				= "требует следующие реагенты:"
	ATSW_REAGENTFRAMETITLE 		= "Для выполнения задач нужны следующие реагенты:"
	ATSW_REAGENTBUTTON 			= "Реагенты"
	ATSW_REAGENTFRAME_CH1 		= "Сумки"
	ATSW_REAGENTFRAME_CH2 		= "Банк"
	ATSW_REAGENTFRAME_CH3 		= "Персонажи"
	ATSW_REAGENTFRAME_CH4 		= "Продавец"
	ATSW_ALTLIST1 						= "в сумках"
	ATSW_ALTLIST2 						= "в банке"
	ATSW_ANDMORE						= "и более..."
	
	ATSW_OPTIONS_TITLE 				= "Настройки Advanced Trade Skill Window"
	ATSWOFTOTALDISPLAY_TEXT 	= "Количество отображается:"
	ATSWOFUCB_TEXT 					= "Едино"
	ATSWOFSCB_TEXT 					= "Раздельно"
	ATSWOFTOTALINCLUDE_TEXT = "Количество включает:"
	ATSWOFIB_TEXT 						= "Банк"
	ATSWOFIA_TEXT 						= "Других персонажей"
	ATSWOFIM_TEXT 						= "Торговцев"
	ATSWOFAB_TEXT 						= "Автопокупка у продавца\n|cff808080Автоматически покупать всё возможное и необходимое \nдля всех предметов в списке задач при разговоре с торговцами|r"
	ATSWOFTB_TEXT 						= "Подсказка для рецептов\n|cff808080Отображение всплывающей подсказки при наведении \nкурсора мыши на рецепт в списке рецептов|r"
	ATSWOFSLB_TEXT 					= "Список покупок под аукционом\n|cff808080Отображать список предметов, необходимых для создания \nвсех предметов в списке задач под окном аукциона|r"
	
	ATSW_TOOLTIP_NECESSARY 		= "Требуемые реагенты:"
	ATSW_TOOLTIP_POSESS			=	"Следующие персонажи имеют"
	ATSW_TOOLTIP_BUYABLE 			= "(продаётся)"
	ATSW_TOOLTIP_INBAGS 			= "Сумки:"
	ATSW_TOOLTIP_INBANK 			= "Банк:"
	ATSW_TOOLTIP_ONALTS 			= "Персонажи:"
	ATSW_TOOLTIP_SAYREAGENTS	= "\n|cff1eff00Shift + ЛКМ|r: |cffffffffОтправить список реагентов в чат|r"
	ATSW_TOOLTIP_ADDITEM			= "\n|cff1eff00Shift + ЛКМ|r: |cffffffffДобавить все предметы в задачи|r"
	ATSW_BUYBUTTON_TOPTEXT 	= "Этот торговец продаёт реагенты, нужные для задач за"
	ATSW_BUYBUTTON_TEXT 			= "Купить реагенты"
	ATSW_SHOPPINGLISTTITLE 		= "Реагенты, нужные для создания предметов в списке заданий:"
	
	ATSW_TOOLS 							= "Инструменты:"
	ATSW_AMOUNT 						= "Кол-во:"
	ATSW_ALL 								= "Все"
	ATSW_ENCHANT 						= "Зачаровать"
	
	ATSW_CSBUTTON 						= "Редактор"
	ATSWCS_TITLE 							= "Редактор сортировки рецептов"
	ATSWCS_TRADESKILLISTTITLE 	= "Рецепты"
	ATSWCS_CATEGORYLISTTITLE	= "Категории"
	ATSWCS_ADDCATEGORYLABEL 	= "Введи имя категории"
	ATSWCS_ADD 							= "Добавить"
	ATSWCS_CATEGORYNAMETITLE 	= "Имя:"
	ATSW_UNCATEGORIZED 			= "Без категории"
	
	BINDING_NAME_SHOWHIDE			=	"Показать / Скрыть"
	
	ATSW_HELP_TITLE					= "Команды поиска"
	ATSW_HELP_REAGENT				= ":reagent |cРеагент|r|n:r |cРеагент|r"
	ATSW_HELP_REAGENT_DESC		= "- показать рецепты, требующие |cРеагент|r для производства"
	ATSW_HELP_LEVEL					= ":level |cУровень|r|n:level |c1 - 10|r|n:level |c45+|r"
	ATSW_HELP_LEVEL_DESC			= "- показать рецепты, которые производят предметы уровня |cУровень|r"
	ATSW_HELP_QUALITY				= ":quality |cКачество|r|n:q |cКачество|r|n:rarity |cКачество|r|n:r |cКачество|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r"
	ATSW_HELP_QUALITY_DESC		= "- показать рецепты, которые производят предметы качества |cКачество|r"
	ATSW_HELP_POSSIBLE				= ":possible |cКоличество|r|n:possible |c10+|r|n:possible |c1 - 40|r"
	ATSW_HELP_POSSIBLE_DESC		= "- показать рецепты, которые можно произвести |cКоличество|r раз, используя материалы в сумках"
	ATSW_HELP_POSSIBLE_TOTAL	= ":possibletotal |cКоличество|r"
	ATSW_HELP_POSSIBLE_TOTAL_DESC = "- показать рецепты, которые можно произвести |cКоличество|r раз, используя материалы в сумках и местах, указанных в настройках (Банк, Другие персонажи или Торговцы)"
	ATSW_HELP_QNAMES					= "Названия качества:"
	ATSW_HELP_QNAMES_DESC		= "|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r"
	ATSW_HELP_QCOLORS				= "Цвета качества:"
	ATSW_HELP_QCOLORS_DESC		= "|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r"
	
else
	ATSW_CLEAR 							= "Clear"
	ATSW_CREATE 							= "Create"
	ATSW_STOP 								= "Stop"
	ATSW_SORTBY 							= "Sort by:"
	ATSW_SORTBYCATEGORY 			= "Category"
	ATSW_SORTBYNAMES 				= "Name"
	ATSW_SORTBYDIFFICULTY			= "Difficulty"
	ATSW_CUSTOMSORTING 			= "Custom"
	ATSW_TASK 								= "Task"
	ATSW_SEARCHLABEL 					= "Search"
	ATSW_REAGENTLIST1 				= "Crafting of"
	ATSW_REAGENTLIST2 				= "require the following reagents:"
	ATSW_REAGENTFRAMETITLE 		= "Your tasks require the following reagents:"
	ATSW_REAGENTBUTTON 			= "Reagents"
	ATSW_REAGENTFRAME_CH1		= "Bags"
	ATSW_REAGENTFRAME_CH2 		= "Bank"
	ATSW_REAGENTFRAME_CH3 		= "Alts"
	ATSW_REAGENTFRAME_CH4 		= "Merchant"
	ATSW_ALTLIST1 						= "in bags"
	ATSW_ALTLIST2 						= "in bank"
	ATSW_ANDMORE						= "and more..."
	
	ATSW_OPTIONS_TITLE 				= "Advanced Trade Skill Window options"
	ATSWOFTOTALDISPLAY_TEXT	= "Total count is displayed:"
	ATSWOFUCB_TEXT						= "Unified"
	ATSWOFSCB_TEXT 					= "Separated"
	ATSWOFTOTALINCLUDE_TEXT 	= "Total count include:"
	ATSWOFIB_TEXT 						= "Bank"
	ATSWOFIA_TEXT 						= "Alternative characters"
	ATSWOFIM_TEXT 						= "Merchant"
	ATSWOFAB_TEXT 						= "Autobuy from merchant\n|cff808080Automatically buy anything possible and necessary for all items \nin the task list when speaking to merchants|r"
	ATSWOFTB_TEXT 						= "Recipe tooltip\n|cff808080Display a tooltip when a mouse cursor is hovering over a recipe \nin the recipe list|r"
	ATSWOFSLB_TEXT 					= "Auction house shopping list\n|cff808080Display a list of items that are required for crafting all items \nin the task list under auction window|r"
	
	ATSW_TOOLTIP_NECESSARY 		= "Required reagents:"
	ATSW_TOOLTIP_POSESS			=	"These characters possess"
	ATSW_TOOLTIP_BUYABLE 			= "(buyable)"
	ATSW_TOOLTIP_INBAGS 			= "Bags:"
	ATSW_TOOLTIP_INBANK 			= "Bank:"
	ATSW_TOOLTIP_ONALTS 			= "Alts:"
	ATSW_TOOLTIP_SAYREAGENTS	= "\n|cff1eff00Shift + Left Click|r: |cffffffffSay reagents required to craft the item|r"
	ATSW_TOOLTIP_ADDITEM			= "\n|cff1eff00Shift + Left Click|r: |cffffffffAdd all items to tasks|r"
	ATSW_BUYBUTTON_TOPTEXT 	= "This merchant sells reagents that are necessary for tasks for"
	ATSW_BUYBUTTON_TEXT 			= "Buy reagents"
	ATSW_SHOPPINGLISTTITLE 		= "Reagents required to create all items in the task list:"
	
	ATSW_TOOLS 							= "Tools:"
	ATSW_AMOUNT 						= "Amount:"
	ATSW_ALL 								= "All"
	ATSW_ENCHANT 						= "Enchant"
	
	ATSW_CSBUTTON 						= "Editor"
	ATSWCS_TITLE 							= "Custom Sorting Editor"
	ATSWCS_TRADESKILLLISTTITLE 	= "Recipes"
	ATSWCS_CATEGORYLISTTITLE 	= "Categories"
	ATSWCS_ADDCATEGORYLABEL 	= "Enter category name"
	ATSWCS_ADD 							= "Add"
	ATSWCS_CATEGORYNAMETITLE 	= "Name:"
	ATSW_UNCATEGORIZED 			= "Uncategorized"
	
	BINDING_NAME_SHOWHIDE			=	"Show / Hide"
	
	ATSW_HELP_TITLE					= "Search commands"
	ATSW_HELP_REAGENT				= ":reagent |cReagent|r|n:r |cReagent|r"
	ATSW_HELP_REAGENT_DESC		= "- show recipes that require |cReagent|r to craft"
	ATSW_HELP_LEVEL					= ":level |cLevel|r|n:level |c1 - 10|r|n:level |c45+|r"
	ATSW_HELP_LEVEL_DESC			= "- show recipes that produce items of |cLevel|r level"
	ATSW_HELP_QUALITY				= ":quality |cQuality|r|n:q |cQuality|r|n:rarity |cQuality|r|n:r |cQuality|r|n:quality |cwhite|r|n:quality |cgreen+|r|n:q |cpoor - uncommon|r"
	ATSW_HELP_QUALITY_DESC		= "- show recipes that produce items of |cQuality|r quality"
	ATSW_HELP_POSSIBLE				= ":possible |cAmount|r|n:possible |c10+|r|n:possible |c1 - 40|r"
	ATSW_HELP_POSSIBLE_DESC		= "- show recipes that can be crafted |cAmount|r times using materials in your bags"
	ATSW_HELP_POSSIBLE_TOTAL	= ":possibletotal |cAmount|r"
	ATSW_HELP_POSSIBLE_TOTAL_DESC = "- show recipes that can be crafted |cAmount|r times using materials in your bags and locations specified in options menu (Bank, Alternative characters or Merchant)"
	ATSW_HELP_QNAMES					= "Quality names:"
	ATSW_HELP_QNAMES_DESC		= "|cff9d9d9dPoor|r, Common|r, |cff1eff00Uncommon|r, |cff0070ddRare|r, |cffa335eeEpic|r, |cffff8000Legendary|r, |cffe6cc80Artifact|r"
	ATSW_HELP_QCOLORS				= "Quality colors:"
	ATSW_HELP_QCOLORS_DESC		= "|cff9d9d9dGrey|r, White|r, |cff1eff00Green|r, |cff0070ddBlue|r, |cffa335eePurple|r, |cffff8000Orange|r, |cffe6cc80Gold|r"
end
